icsharpcode/ILSpy

- ILSpy/LoadedAssembly.cs
- ILSpy/TreeNodes/AssemblyTreeNode.cs
Today the Assembly tree view in ILSpy only show assembly name. If different version of the same dlls are included, they appear the same and is confusing. You have to click the entry and check the details on the right panel. That happens a lot when work with both .Net 3.5 and 4.0/4.5.
The change is to include dll version in the name.
> Update ILSpy to show assembly version in the assembly tree view

- ILSpy/ILSpy.csproj
- ILSpy/TreeNodes/Analyzer/AnalyzedTypeTreeNode.cs
- ILSpy/TreeNodes/Analyzer/AnalyzedTypeUsedByTreeNode.cs
The "Used By" analyzer node on types, is very handy to quickly find type references.
This PR is an implementation for that in ILSpy:
Here is the Reflector output on the same assembly list:
Seb
> Add a new "Used By" analyzer node on types

- ILSpy/AssemblyList.cs
- ILSpy/LoadedAssembly.cs
- ILSpy/MainWindow.xaml.cs
- ILSpy/TreeNodes/AssemblyReferenceTreeNode.cs
When writing an ILSpy plugin (in my case Reflexil), it is very useful to:
- know when the selected node(s) is changed, so that the plugin can react in sync with the user selection. You already consume SelectionChanged from the TreeView, so we can easily forward this with a SelectionChanged event directly exposed by the MainWindow.
- use the AssemblyReferenceTreeNode node and its AssemblyNameReference object. In my case, Reflexil is able to deal with such objects.
- Hot replace an assembly from stream so that ILSpy and Reflexil can exchange data, without the need to share the same Mono.Cecil implementation.
Regards
S.L.
> Allow Reflexil integration

- ILSpy/CommandLineArguments.cs
- ILSpy/MainWindow.xaml.cs
This adds a new command line argument "/search:keyword", which will open the search pane with the given keyword.
> Search as command line argument

- ILSpy/SearchPane.cs
Support for using regular expressions or "search type" directly in the textbox.
For instance, one can type t:foo to find types that contains "foo" in the name (*m* for members and *c* for constants)
Also, regular expressions can be entered quoted in */* and */*. For instance, t:/^foo$/ search for types named exactly as *foo*
> Improved search

- ICSharpCode.Decompiler/Ast/AstMethodBodyBuilder.cs
- ICSharpCode.Decompiler/CecilExtensions.cs
- ICSharpCode.Decompiler/Tests/ValueTypes.cs
Due to incorrect translation of Cgt_Un and Cle_Un for signed types I had trouble disassembling something like the folowing code fragment:
```
var p1 = 0;
var p2 = 1; 
bool pivotsDiffer = p1.CompareTo(p2) != 0;
```
which was disassembled to
```
var p1 = 0;
var p2 = 1; 
bool pivotsDiffer = p1.CompareTo(p2) > 0;
```
I fixed this specific issue when comparing signed integral types with 0 using Cgt_Un or Cle_Un
> added fix for unsigned comparison with signed integral types;

- ILSpy/Languages/CSharpLanguage.cs
- ILSpy/VB/VBLanguage.cs
Global types are used as assembly initializers; they contain global methods (e.g. in VB), and may be used by obfuscators. They can also be renamed so they are hard to find (default name is "&lt;Module&gt;").
> Display a reference to a module's global type.

- ICSharpCode.Decompiler/ILAst/AsyncDecompiler.cs
AsyncDecompiler lost track of state machine variable when analyzing a try/catch block.
> Fix for issue #612

- ILSpy/ILSpySettings.cs
A small change that allows ILSpy to run self-contained, I thought some other people may find it useful. This simply checks if a settings file exists in the same directory as the executable and, if so, uses that instead of ApplicationData.
> Portable settings file

- ILSpy/Options/DisplaySettings.cs
- ILSpy/Options/DisplaySettingsPanel.xaml
- ILSpy/Options/DisplaySettingsPanel.xaml.cs
- ILSpy/TextView/DecompilerTextView.cs
For those of us on small monitors or who just dislike horizontal scrollbars, this adds an 'Enable word wrap' option to the Display settings, which causes the decompilation view to wrap if enabled.
> Added word wrapping

- ICSharpCode.Decompiler/Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler/Tests/packages.config
With these changes, the TestRunner integrated in VS can be used to run the Unit Tests:
(I just installed the package over the GUI, the project file was modified by nuget)
> add nunit runner as nuget so tests can be run in the TestExplorer in VS

- ICSharpCode.Decompiler/ILAst/StateRange.cs
- ICSharpCode.Decompiler/Tests/Async.cs
This resolves issue https://github.com/icsharpcode/ILSpy/issues/675 by checking if ast matches to very specific case
> FIX #675. Decompile empty async void methods

- ILSpy/Commands/OpenCommand.cs
- ILSpy/Commands/OpenFromGacCommand.cs
- ILSpy/Commands/OpenListCommand.cs
- ILSpy/Commands/RefreshCommand.cs
- ILSpy/Options/OptionsDialog.xaml.cs
- ILSpy/SearchPane.cs
The following menu items now have an ellipses (...) because they open a
new dialog:
File -> Open...
File -> Open from GAC...
File -> Open List...
View -> Search...
View -> Options...
> Add ellipses to menu items

- ILSpy.AddIn/ILSpyAddIn.vsct
- ILSpy.AddIn/ILSpyAddInPackage.cs
- ILSpy.AddIn/PkgCmdID.cs
- ILSpy.AddIn/Utils.cs
Addresses #694. Supports methods, enums, delegates, properties, interfaces, events and classes.
Changes (only) to ILSpy.AddIn project:
add: code window context menu item "Open code in ILSpy"
add: OpenCodeItemInILSpyCallback does the work, using Visual Studio code model to interrogate source at selection point
change: add additional argument support to OpenAssemblyInILSpy (to support "/navigateTo")
Tested by running the AddIn via Debug > Start New Instance.
Using Visual Studio Pro 2013 for development and testing.
TODO: disambiguate overloaded methods by number and type of parameters
(Note: I have used C# and git for a long time, but I am new to GitHub and open source contributions. Please be gentle ...)
> Add an "Open in ILSpy" option to the context menu in the code window.

- ILSpy/Controls/ResourceStringTable.xaml
Allow grid listview with resource tables to scroll items that are higher then the listview rows.
> Allow scrolling in high resource rows

- ILSpy.AddIn/CodeElementXmlDocKeyProvider.cs
- ILSpy.AddIn/Samples/ILSpyAddInSamples.cs
Follow-up to #697, address remaining issue with multi-dimensional arrays. Used @dgrunwald's suggestion of generating XML documentation for my test cases and determining the required ID strings accordingly.
Cases such as this are now handled correctly:
`public void GenericClassGenericMethod<T3, T4>(int[] x, SomeGenericClass<T3[], T4[,,]>[,,] y)`
Note that no attempt was made to handle non-standard array bounds -- these cannot be declared in C#, so should be OK at least for C# projects. I have not tested any of this with languages other than C#.
See updated Samples/ILSpyAddInSamples.cs to see all cases that have been tested.
> Fix "Open code in ILSpy" for overloaded methods with multi-dimensional array parameters.

- ILSpy.BamlDecompiler/Ricciolo.StylesExplorer.MarkupReflection/XmlBamlReader.cs
We faced a situation when csc submits TypeSerializerInfo into the baml being generated. ILSpy doesn't support it so it fails to decompile the baml. From the MSFT source code the binary layout for TypeSerializedInfo is the same as for TypeInfo, so i just added TypeSerializerInfo handling the same way it was done for TypeInfo.
> Support for BamlRecordType.TypeSerializerInfo in bamlreader

- ILSpy/LoadedAssembly.cs
This duplicates the logic from jbevain/cecil#279 and allows assemblies with Portable PDBs to be opened in ILSpy. This fixes #723.
> Validate the PDB type.

- ICSharpCode.Decompiler/Ast/TextTokenWriter.cs
I've found that significant improvement could be applied to the ILSpy. Consider the following code:
Unfortunately, the `base` and `this` words near the constructors are not clickable. 
I've extended code to make them clickable. They will point to appropriate ctor definition.
That will hugely simplify the code navigation.
P.S. I've created issue in NRefactory project ([#519](https://github.com/icsharpcode/NRefactory/issues/519)), but later realized that it's a pure ILSpy issue.
> Add reference to _this_ and _base_ keywords in ctor initializer

- ILSpy/MainWindow.xaml.cs
Fixed two issues.
The first issue is just a typo and top panel size was not saved on tool close.
The second issue leaded to the small pane size when it's displayed. Consider the following scenario:
- You open the `Source code` and the `Search panel`. After that you use a grid resizer and make the panels the same height. Resizer assigned heights `250*` and `250*`. Yes, resizer assigns values greater than 1.
- You open the `Analyze` panel. Tool finds from the settings that the bottom pane ratio comparing to the source code is `0.5`. As result, heights become the following:
- top pane: `250*`
- text view: `0.5*`
- bottom pane: `0.5*`
Obviously, the top pane became a "Godzilla", while rest panels took their minimum.
In order to avoid such issues, I run normalization and ensure that all …
> Ui improve pane experience

- .editorconfig
- Rebracer.xml
* Code style is converted where possible, except for naming rules
* Editing preferences that don't impact code style are removed
> Convert most Rebracer rules to .editorconfig (natively supported by VS)

- ICSharpCode.Decompiler.Tests/CorrectnessTestRunner.cs
- ICSharpCode.Decompiler/IL/ControlFlow/AsyncAwaitDecompiler.cs
Original:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace ILSpyBugs
{
class Class1
{
private static async Task<T> RequestResultAsync<T>()
{
return await Task.Run(async delegate {
return default(T);
});
}
}
}
```
Was decompiled to:
```
// ILSpyBugs.Class1
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
internal class Class1
{
private static async Task<T> RequestResultAsync<T>()
{
TaskAwaiter<T> taskAwaiter = Task.Run<T>((Func<Task<T>>)(() => default(T))).GetAwaiter();
if (!taskAwaiter.IsCompleted)
{
await taskAwaiter;
TaskAwaiter<T> taskAwaiter2 = default(TaskAwaiter<T>);
taskAwaiter = taskAwaiter2;
int num;
int num2 = num = -1;
}
return taskAwaiter.GetResult();
}
}
```
Now …
> Fix await calls not getting decompiled correctly

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.opt.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.roslyn.il
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/IL/ILReader.cs
- ICSharpCode.Decompiler/IL/Instructions/DefaultValue.cs
- ICSharpCode.Decompiler/IL/Transforms/AssignVariableNames.cs
- ICSharpCode.Decompiler/IL/Transforms/EarlyExpressionTransforms.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformCollectionAndObjectInitializers.cs
- ICSharpCode.Decompiler/Util/CollectionExtensions.cs
> Initializer

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.nuspec.template
- ILSpy.AddIn/ILSpy.AddIn.csproj
- ILSpy.BamlDecompiler.Tests/ILSpy.BamlDecompiler.Tests.csproj
- ILSpy.BamlDecompiler/ILSpy.BamlDecompiler.csproj
- ILSpy/ILSpy.csproj
- TestPlugin/TestPlugin.csproj
- clean.bat
- debugbuild.bat
- releasebuild.bat
The current submodule and bundling approach causes problems for consumers of **ICSharpCode.Decompiler** due to the embedding of a "non-standard" build of **Mono.Cecil.dll**. This pull request modifies the references to use `PackageReference` instead, and declare a NuGet dependency on the Mono.Cecil package on NuGet.
For this pull request, I did not remove the submodule itself. It's possible that developers have local branches in the submodule and would like to continue working with those branches, so I decided to leave that decision for a future pull request.
This pull request is very similar to #998. Specific differences are:
1. This pull request leaves the **cecil** submodule in place, and updates the commit reference to match the commit we're referencing as a NuGet package
2. This pull …
> Reference Mono.Cecil using a PackageReference

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/AsyncMain.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/AsyncMain.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/AsyncMain.roslyn.il
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/IL/ControlFlow/AsyncAwaitDecompiler.cs
Adds the feature described in #1023 
I had a bit of a hard time writing the test since, until now, all tests generated DLLs and we need to generate an EXE to test that the entry point is decompiled correctly. I created a second method called `RunForLibrary()` to replace the old one and set the necessary flags to generate DLLs. This way we can use the `Run()` method to create an EXE file.
At this point, I don't see any other way to identify the generated method but by its name (see [Roslyn](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/Symbols/Synthesized/SynthesizedEntryPointSymbol.cs,18)). I put the logic to identify the method in the `AsyncAwaitDecompiler` since more checks could be added in the future to distinguish it.
> Add support for async main method

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpFormattingOptions.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ILSpy/Controls/BoolToVisibilityConverter.cs
- ILSpy/ILSpy.csproj
- ILSpy/Options/DecompilerSettingsPanel.xaml
- ILSpy/Options/DecompilerSettingsPanel.xaml.cs
> DecompileMemberBodies setting

- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/TextWriterTokenWriter.cs
- ICSharpCode.Decompiler/CSharp/Syntax/CSharpModifierToken.cs
- ICSharpCode.Decompiler/IL/ILReader.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformExpressionTrees.cs
- ICSharpCode.Decompiler/TypeSystem/TypeSystemExtensions.cs
- ICSharpCode.Decompiler/Util/CollectionExtensions.cs
This reduces allocations for a full decompilation about 3% (CPU time is also reduced about 3-4%).
_Because I haven't contributed for a long time to ILSpy I'm not sure if these changes have acceptable quality and style. Most of them are independent of each other, so I can remove some of them based on feedback._
> Reduced allocations

- ICSharpCode.Decompiler/IL/ControlFlow/AsyncAwaitDecompiler.cs
- ICSharpCode.Decompiler/IL/Transforms/ILInlining.cs
This reduces allocations for a full decompilation about 4% (CPU time is also reduced about 4%).
Additionally, it fixes a few rare cases where `ILInlining` was too aggressive when `topLevelInst.ILRange` was not set (e.g., when decompiling `ICSharpCode.Decompiler.DotNetCorePathFinder` or `System.Diagnostics.Tracing.TypeAnalysis`).
> Reduced allocations in ILInlining

- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExceptionHandling.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExceptionHandling.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExceptionHandling.opt.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExceptionHandling.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExceptionHandling.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Loops.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Loops.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Loops.mcs.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Loops.opt.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Loops.opt.mcs.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Loops.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Loops.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.opt.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.roslyn.il
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/IL/ControlFlow/ConditionDetection.cs
- ICSharpCode.Decompiler/IL/Transforms/HighLevelLoopTransform.cs
A solution to #1133 involving repeated inlining, and block exit merging with appropriate keyword prioritisation
> Improve control flow decompilation (fixes #1133)

- ILSpy/SearchStrategies.cs
Added the ability to have partial search matches when fullNameSearch is false and allowNonContiguousMatch is true. It is possible to use the in-word matching even with the full name search but since the full names are quite long, a lot of irrelevant matches are picked up.
> Feature Request: Search by abbreviated qualified name #1090

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.opt.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ShortCircuit.roslyn.il
- ICSharpCode.Decompiler/IL/Transforms/EarlyExpressionTransforms.cs
- ICSharpCode.Decompiler/IL/Transforms/ExpressionTransforms.cs
Roslyn replaces logical AND operators with bitwise operators, if the right hand side has no side-effects and relatively little performance cost (such as ldloc).
~The proposed solution is by no means comprehensive, but it might be a start. Perhaps `ExpressionTransforms` would be a better place than `EarlyExpressionTransforms`. I wanted it to go before `ConditionDetection` but I don't think it matters.~
> Reverse Roslyn optimisation to favour && over & on boolean operands.

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.opt.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.roslyn.il
- ICSharpCode.Decompiler/IL/Transforms/SplitVariables.cs
This should fix #1251. I am not sure if we can treat callvirt instructions the same as call instructions, but I think this should be no problem.
> A possible fix for Issue 1251

- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Switch.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Switch.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Switch.opt.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Switch.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Switch.roslyn.il
- ICSharpCode.Decompiler/IL/ControlFlow/ConditionDetection.cs
- ICSharpCode.Decompiler/IL/ControlFlow/LoopDetection.cs
- ICSharpCode.Decompiler/IL/ControlFlow/SwitchAnalysis.cs
- ICSharpCode.Decompiler/IL/ControlFlow/SwitchDetection.cs
- ICSharpCode.Decompiler/IL/Transforms/HighLevelLoopTransform.cs
- ICSharpCode.Decompiler/IL/Transforms/SwitchOnStringTransform.cs
- ICSharpCode.Decompiler/Util/CollectionExtensions.cs
This PR contains a number of commits aimed at improving code quality surrounding [potential] switch statements. It primarily addresses two issues currently producing unnecessary gotos.
`SwitchDetection.UseCSharpSwitch` is over-aggressive, resulting in the replacement of condition trees with much poorer looking switch statements. A number of heuristics are added to better discern which representation to use.
`LoopDetection.DetectSwitchBody`, `FindExitPoint` and associated loop partitioning code is unaware of the interaction between switch statements and `continue` resulting in poor exit point selection when cases can leave the switch body via a branch to a continue block
The test cases added with each commit are the best place to look for a concise before/after. Unfortunately the number of …
> Improve switch statement decompilation

- ICSharpCode.Decompiler.Tests/TestCases/Correctness/Loops.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Issue959.cs
- ICSharpCode.Decompiler/IL/ControlFlow/SwitchAnalysis.cs
This fixes a failing assertion in `SwitchDetection` (debug mode) because blocks get added to `InnerBlocks` but not to the switch `Sections`. Previously the redundant/unreachable code got removed.
> Abort SwitchAnalysis on duplicate condition (redundant code)

- ICSharpCode.Decompiler/Metadata/MetadataExtensions.cs
- ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs
Fixes issue with opening .NET 3.x assemblies, as they use the 2.0 mscorlib.
Fixes #1346
> Update UniversalAssemblyResolver to include missing .NET 3.x support

- ILSpy/AboutPage.cs
- ILSpy/FilterSettings.cs
- ILSpy/LoadedNugetPackage.cs
Fixes issue #1362 Removed string literals and utilized nameof()
> Fix 1362 Removed string literals in favor of nameof usage

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/QueryExpressions.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/QueryExpressions.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/QueryExpressions.opt.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/QueryExpressions.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/QueryExpressions.roslyn.il
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/CSharp/Transforms/CombineQueryExpressions.cs
- ICSharpCode.Decompiler/CSharp/Transforms/IntroduceQueryExpressions.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/IL/Transforms/CombineExitsTransform.cs
- ICSharpCode.Decompiler/IL/Transforms/DelegateConstruction.cs
- ICSharpCode.Decompiler/Output/TextTokenWriter.cs
* Add CombineExitsTransform: Merges `if (cond) return cond2; else return false;` or similar to `return cond && cond2;` in lambdas
* Fixed some bugs in QueryExpressions transforms.
* Fix linking in query expressions.
> Combine exitpoints in lambdas

- ILSpy/Search/AbstractSearchStrategy.cs
- ILSpy/Search/LiteralSearchStrategy.cs
- ILSpy/Search/MemberSearchStrategy.cs
- ILSpy/Search/MetadataTokenSearchStrategy.cs
- ILSpy/Search/SearchPane.cs
- ILSpy/Search/SearchPane.xaml
- Improved performace of searching (though without parallelism, I've done some testing and it's not efficient).
- Search results are filtered using API visibility option - this is usefull e.g. if you want to find only methods that are public, so you can use them (I was in that situation few times and I think there was issue requesting that). Old behaviour was little odd, you could search for something but not navigate to it becouse of visibility option.
> Improve searching

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ConstantsTests.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
Changes
`(enumValue & SomeEnum.SomeValue) == SomeEnum.None`
to
`(enumValue & SomeEnum.SomeValue) == 0`
> Fix #1462: Inconsistent enum flag check

- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
Fixed crash then type is null in type def matches. Encountered while decompiling assembly and saving it as project.
> Fixed crash then type is null in type def matches.

- README.md
Add the .NET Core SDK 3 requirement, otherwise the projects fail to load.
> add .NET Core SDK 3 requirement

- appveyor.yml
The VS2019 preview image is super-old. Necessary change: choco install latest 3.0 SDK.
Was: msbuild version 16.0.360.33175
Now: msbuild version 16.1.76.45076
> AppVeyor: Switch from Preview Image to RTM Image

- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/IL/ILVariable.cs
- ICSharpCode.Decompiler/IL/Transforms/DelegateConstruction.cs
- ICSharpCode.Decompiler/IL/Transforms/RemoveDeadVariableInit.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformCollectionAndObjectInitializers.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformDisplayClassUsage.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformExpressionTrees.cs
This pull request refactors the `TransformDisplayClassUsage` part of `DelegateConstruction` into a separate decompilation step. This removes an implicit dependency of `TransformExpressionTrees` on `DelegateConstruction` which will be a blocker, if we ever want to support local functions. 
Previously all "display classes" were transformed by `DelegateConstruction`, even the ones used by expression trees.
This pull request includes:
* a fix for #1026: Now we construct a "display class" from the fields of the state-machine type and replace all uses of `ldfld/stfld stateMachineField(ldloc this, ...)` with the variables introduced by the `YieldReturnDecompiler`.
* a fix for #1554: Relax patterns for closure detection. Take a look at the structure of the type, not just the compiler-generated …
> Improved support for closures generated by Mono C# compiler

- ILSpy/ContextMenuEntry.cs
- ILSpy/ILSpy.csproj
- ILSpy/MainWindow.xaml.cs
- ILSpy/Search/AbstractEntitySearchStrategy.cs
- ILSpy/Search/AbstractSearchStrategy.cs
- ILSpy/Search/LiteralSearchStrategy.cs
- ILSpy/Search/MemberSearchStrategy.cs
- ILSpy/Search/MetadataTokenSearchStrategy.cs
- ILSpy/Search/ResourceSearchStrategy.cs
- ILSpy/Search/SearchPane.cs
- ILSpy/Search/SearchResult.cs
- ILSpy/TreeNodes/AssemblyListTreeNode.cs
Adds searching resources including .resource files and tree navigation. Because of recent changes to cache entity result icons, I combined the approaches of myself and @sailro, splitting both results and strategies.
> Resource search strategy

- ILSpy.BamlDecompiler/ILSpy.BamlDecompiler.csproj
- ILSpy/ILSpy.csproj
- appveyor.yml
- global.json
Note: won't build atm because AppVeyor still uses a VS 2019 image pre-16.3.
> .NET Core 3 Final Updates

- ICSharpCode.Decompiler/Metadata/MetadataExtensions.cs
- ILSpy/ILSpy.csproj
- ILSpy/Search/AssemblySearchStrategy.cs
- ILSpy/Search/SearchPane.cs
- ILSpy/Search/SearchResult.cs
Searching assemblies by full name. Shows file path in Location column.
> Add assembly search strategy

- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- global.json
This does not yet solve the problem that
* Check out into a new directory
* Open ILSpy.sln in VS
* Build
fails because BamlDecompiler and others start building before ILSpy.csproj actually builds. Funnily, Rebuild All immediately after works fine.
> Removing csproj Hacks

- README.md
Fixes #1729
Based on VS community 16.3 installation on a blank Windows 10 1903 September VM.
> Document current dependencies for master

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/NoForEachStatement.Expected.cs
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/NoForEachStatement.cs
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/NoForEachStatement.il
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/NoForEachStatement.opt.il
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/NoForEachStatement.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/NoForEachStatement.roslyn.il
- ICSharpCode.Decompiler.Tests/UglyTestRunner.cs
- ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
When decompiling a foreach loop on an IEnumerable, if "Detect foreach statements" is turned off, there is a NullReferenceException thrown in StatementBuilder.
The `resource` parameter is set to null here:
https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/CSharp/StatementBuilder.cs#L452
And then deferenced at the `resource.Detach()` call here:
https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/CSharp/StatementBuilder.cs#L423
This simple change fixes the issue and decompilation works as expected.
Before:
After:
I couldn't find any existing test infrastructure for validating settings, but if a test is required and there is documentation to do so, please let me know. It doesn't seem like the existing test infrastructure is well suited to variations …
> Fix NullReferenceException when foreach decompilation is turned off

- ICSharpCode.Decompiler/CSharp/OutputVisitor/TextWriterTokenWriter.cs
.NET Core fixed some round trip formatting with floats https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/
When decompiling `-0f` on .NET Core, ILSpy currently outputs `--0f` which is a compile error. Simplest reproducible test case:
```cs
using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.CSharp.OutputVisitor;
using ICSharpCode.Decompiler.TypeSystem;
using System;
using System.Linq;
using System.Reflection;
namespace DecompilerTesting
{
class Program
{
static void Main(string[] args)
{
var decompiler = new CSharpDecompiler(Assembly.GetExecutingAssembly().Location, new DecompilerSettings());
var method = decompiler.TypeSystem.MainModule.GetTypeDefinition(new …
```
> Fix extra minus sign when formatting -0 on .NET Core 3.0

- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
An interface method with the following IL representation
```
.method public specialname rtspecialname instance void _VtblGap1_2 () runtime managed
```
Decompiles with a a sealed modifier and doesn't recompile because it has no body. I assume only methods in interfaces can be sealed.
> Fix sealed modifier on interface methods with no body

- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
- ICSharpCode.Decompiler/TypeSystem/ParameterizedType.cs
@dgrunwald Please review my changes to `DecompiledLambdaResolveResult`.
An alternative solution might be to create an implementation of `LambdaResolveResult` that does not use `ILFunction` at all. This might have been a better idea...
> #1749: Represent multi-instruction BlockContainers as inlined delegate invocation.

- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ILSpy/TreeNodes/TypeTreeNode.cs
Change both the icon of `System.Void` in left assemblies tree and decompile result of `System.Void` to struct.
> Display System.Void as struct

- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs
- ICSharpCode.Decompiler/Metadata/DotNetCorePathFinder.cs
- ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs
- ICSharpCode.Decompiler/TypeSystem/TypeSystemExtensions.cs
* Adds some kind of support to `DotNetCorePathFinder` so that we treat .netstandard 2.1 libraries as .net core version 3.0 at least.
* Fixes #1785
@tamlin-mike
> netstandard2.1 fixes

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Async.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CustomTaskType.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/DelegateConstruction.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/LocalFunctions.cs
- ICSharpCode.Decompiler/CSharp/CallBuilder.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ICSharpCode.Decompiler/IL/ILReader.cs
- ICSharpCode.Decompiler/IL/Transforms/DelegateConstruction.cs
- ICSharpCode.Decompiler/IL/Transforms/LocalFunctionDecompiler.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformDisplayClassUsage.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/LocalFunctionMethod.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
Try add basic support for generic local function(fix #1588) and static local function(C#8.0), and fix some other issue found for local function.
Limited and Known Issue(not fixed):
1. Due to some [break changes](https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20post%20VS2019.md) and some other issues fixed in roslyn 16.4, `static local function` is incompatible with old versions of roslyn.
```cs
//It compile on 16.3 as non-static, and fixed in 16.4. The generic version still compile on 16.4 and already reported as roslyn#39706
public void Roslyn_LE_16_3() {
int i = 0;
ZZ1();
int ZZ() => i;
static void ZZ1(){
ZZ();
}
}
//It's able to compile this on 16.4+ but not 16.3
public void Roslyn_GE_16_4() {
ZZ1();
static void ZZ(){}
static void …
```
> Add support for generic and static local function

- ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs
- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/Properties/AssemblyInfo.cs
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
- ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml
- ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml.cs
- ILSpy.ReadyToRun/ReadyToRunOptions.cs
- ILSpy.sln
- ILSpy/LoadedAssembly.cs
- ILSpy/LoadedAssemblyExtensions.cs
- ILSpy/README.txt
- ILSpy/TextView/Asm-Mode.xshd
- NuGet.config
- README.md
- doc/license.txt
Fixes #1864
This PR introduces `ILSpy.ReadyToRun`, a plugin for disassembling pre-compiled methods contained in a ready-to-run image.
The code is the same as what I wrote before arranged as a plugin.
@christophwille
> Introducing ILSpy.ReadyToRun

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
Updating the package to include latest bug fixes:
- Fixes the crash parsing x86 System.Private.CoreLib (https://github.com/dotnet/runtime/pull/1299)
- Fixes the GC hole when constructing an instance of R2RReader (https://github.com/dotnet/runtime/pull/1263)
- Eliminate `ELEMENT_TYPE_NATIVE_ARRAY_TEMPLATE_ZAPSIG` as a reaction to a runtime optimization (https://github.com/dotnet/runtime/pull/1201)
> ReadyToRun bug fixes

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
Another accumulated fixes for `ILCompiler.Reflection.ReadyToRun`
- Fixed some GCInfo decoding issue
- Make DebugInfo/EHInfo parsing lazy
Along with the fixes, I put in refactoring to get rid of `R2R` from the names and replaced them with `ReadyToRun`. Many of the changes in `ReadyToRunLanguage` is simply that.
> Display ReadyToRun header information

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
Fixes #1888 
This fix should make loading `System.Private.CoreLib.dll` appear instant. This change includes:
- https://github.com/dotnet/runtime/pull/1657
- https://github.com/dotnet/runtime/pull/1899
- https://github.com/dotnet/runtime/pull/31646
- https://github.com/dotnet/runtime/pull/32682
This fix also includes some work from @trylek to support a new initiative in the runtime called [composite R2R](https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/readytorun-format.md). As of now, the technology is not released yet, so it does not harm to not support it in the moment.
> [ILSpy.ReadyToRun] Avoid eager parsing

- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- README.md
- appveyor.yml
- azure-pipelines.yml
pwsh is supported by both our build systems:
* https://www.appveyor.com/docs/windows-images-software/#powershell
* https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md
Advantage: *nix and Mac can easily use ics.d.csproj (needed a symlink previously)
Disadvantage: on Windows the new PowerShell needs to be installed (up until now we relied on Windows PowerShell which comes by default)
> Switch from powershell to pwsh

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
This change reflects the latest change in the `ILCompiler.Reflection.ReadyToRun` package.
The latest change has public API changes, so I think it is a good idea to make sure things keep in sync.
There are some refactorings done to existing code, this is to make future work easier. In particular, with the  `readyToRunMethod` and `runtimeFunction` available, we can start to weave information into the disassembly.
> Upgrade ready to run binary

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
This is part of #1886
Here is an illustration of how the disassembly of the `Int64.Parse()` method looks before and after the decoration.
**Before**
```
; Int64 System.Int64.Parse(String)
000000000047E8E0 4883EC38             sub       rsp,38h
000000000047E8E4 33C0                 xor       eax,eax
000000000047E8E6 4889442428           mov       [rsp+28h],rax
000000000047E8EB 4885C9               test      rcx,rcx
000000000047E8EE 7431                 je        short 0000`0000`0047`E921h
000000000047E8F0 488D410C             lea       rax,[rcx+0Ch]
000000000047E8F4 8B5108               mov       edx,[rcx+8]
000000000047E8F7 488D4C2428           lea       rcx,[rsp+28h]
000000000047E8FC 488901               mov       [rcx],rax
000000000047E8FF 895108               mov       [rcx+8],edx …
```
> Decorate the ready to run disassembly with DebugInfoBounds

- ILSpy/Languages/CSharpLexer.cs
- ILSpy/TextView/BracketHighlightRenderer.cs
Sources:
1) https://github.com/icsharpcode/SharpDevelop/blob/f96b37170c3034aa932dcd33eb3a6fa40e783b95/src/AddIns/DisplayBindings/AvalonEdit.AddIn/Src/BracketHighlightRenderer.cs
2) CSharpLexer.cs is a (later cleaned up) mashup of:
* https://github.com/icsharpcode/SharpDevelop/blob/f96b37170c3034aa932dcd33eb3a6fa40e783b95/src/Libraries/NRefactory/Project/Src/Lexer/AbstractLexer.cs
* https://github.com/icsharpcode/SharpDevelop/blob/f96b37170c3034aa932dcd33eb3a6fa40e783b95/src/Libraries/NRefactory/Project/Src/Lexer/ILexer.cs
* https://github.com/icsharpcode/SharpDevelop/blob/f96b37170c3034aa932dcd33eb3a6fa40e783b95/src/Libraries/NRefactory/Project/Src/Lexer/CSharp/Lexer.cs
* https://github.com/icsharpcode/SharpDevelop/blob/f96b37170c3034aa932dcd33eb3a6fa40e783b95/src/Libraries/NRefactory/Proj …
> Change license headers of two remaining files to the correct MIT header.

- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/CSharp/SequencePointBuilder.cs
- ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
- ICSharpCode.Decompiler/CSharp/Syntax/Statements/TryCatchStatement.cs
- ICSharpCode.Decompiler/IL/Instructions/ILInstruction.cs
- ICSharpCode.Decompiler/IL/Instructions/TryInstruction.cs
- ICSharpCode.Decompiler/IL/Transforms/ExpressionTransforms.cs
(complete rewrite based on our discussions and @jacdavis's work)
> Fix #1919: Use unmapped IL offsets at the start of a catch-block for the 'exception specifier' sequence point.

- ILSpy.AddIn/ILSpy.AddIn.csproj
- ILSpy/ILSpy.csproj
- ILSpy/MainWindow.xaml.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
This pull request adds the capability to extract self-contained executables to ILSpy.
Currently the user is asked to pick a directory where the files are extracted to. Then these files can be loaded by ILSpy normally.
Alternative suggestion: We could create a new assembly list out of all extracted modules.
> Fix #2013: Add option to extract self-contained executables (PublishSingleFile).

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
- ILSpy/MainWindow.xaml.cs
Here is my attempt to describe the callees - see the samples to see how it looks like:
Some of the added descriptions can be clicked to navigate to the associated definitions!
**Here is how it looks like before the change:**
```
; Int64 System.Int64.Parse(String)
; Prolog
000000000047E8E0 4883EC38             sub       rsp,38h
000000000047E8E4 33C0                 xor       eax,eax
000000000047E8E6 4889442428           mov       [rsp+28h],rax
; IL_0000
000000000047E8EB 4885C9               test      rcx,rcx
000000000047E8EE 7431                 je        short 0000`0000`0047`E921h
; IL_000a
000000000047E8F0 488D410C             lea       rax,[rcx+0Ch]
000000000047E8F4 8B5108               mov       edx,[rcx+8]
000000000047E8F7 488D4C2428           lea       rcx,[rsp+28h]
000000000047E8FC …
```
> Using import cell name to describe callees

- ILSpy.Tests/Analyzers/MemberImplementsInterfaceAnalyzerTests.cs
- ILSpy.Tests/ILSpy.Tests.csproj
- ILSpy/Analyzers/Builtin/EventImplementedByAnalyzer.cs
- ILSpy/Analyzers/Builtin/MemberImplementsInterfaceAnalyzer.cs
- ILSpy/Analyzers/Builtin/MethodImplementedByAnalyzer.cs
- ILSpy/Analyzers/Builtin/PropertyImplementedByAnalyzer.cs
- ILSpy/ILSpy.csproj
Resolves #1998 
A new analyzer for the interface implementation lookup. The analyzer can be used on any non-`static` members of classes and structs. The analyzer shows a new `Implements` node for those members that implement an interface (implicitly or explicitly). Abstract members are considered as implementation. Overridden virtual members of base classes are not considered.
I also added the [Moq](https://github.com/moq/moq4) library into the `ILSpy.Tests` test project. If you'd like to use another mocking library, let me know - I'll change that.
> Add new 'Implements' analyzer for interface implementation lookup

- ICSharpCode.Decompiler/Disassembler/OpCodeInfo.cs
- ILSpy/Commands/SearchMsdnContextMenuEntry.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/Properties/Resources.zh-Hans.resx
Currently the "Search MSDN" button results in a "page not found" message on the MSDN website. This PR:
1. Updates the links to point to the new location of the documentation on docs.microsoft.com.
2. Relies on the browse redirecting to the correct language page. Currently docs.microsoft.com does not elegantly handle language codes it does not recognize.
3. Change menu item text to reflect the new website's name.
I did not change any of the internal class name references to MSDN yet.
> Update links to Microsoft Docs.

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExpressionTrees.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ReduceNesting.cs
- ICSharpCode.Decompiler/IL/Transforms/ReduceNestingTransform.cs
Improves 2 things:
Primarily, instructions with containers were not visited so if a method was contained in a try catch it was ignored by the transform. Handling statements with containers required some more detection logic for distinguishing fall-through container leave instructions from keywords (break/return/continue)
Also improves the visual balancing heuristic to consider the number of statements in nested containers (such as above and lambdas).
See additional test cases for things which now decompile more nicely and didn't before.
> Improve ReduceNestingTransform by considering nested containers (Try/Using/Lock/Pinned/etc)

- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
- ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml
- ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml.cs
- ILSpy.ReadyToRun/ReadyToRunOptions.cs
Here I tried to add unwindinfo to the print out, as well as adding an option to turn it on or off.
Before the change it would look like:
```
; Void System.IO.BinaryReader.Dispose()
; Prolog
000000000083FC50 55                   push      rbp
000000000083FC51 4883EC20             sub       rsp,20h
000000000083FC55 488D6C2420           lea       rbp,[rsp+20h]
000000000083FC5A 48894D10             mov       [rbp+10h],rcx
; IL_0000
000000000083FC5E 90                   nop
; IL_0001
000000000083FC5F 488B4D10             mov       rcx,[rbp+10h]
000000000083FC63 BA01000000           mov       edx,1
000000000083FC68 488B4510             mov       rax,[rbp+10h]
000000000083FC6C 488B00               mov       rax,[rax]
000000000083FC6F 488B4048             mov       rax,[rax+48h]
; IL_0003 …
```
> Added UnwindInfo as an optional printout

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/ILPrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/CallIndirect.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/CallIndirect.il
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Unsafe.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Unsafe.il
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
- ICSharpCode.Decompiler/CSharp/Syntax/DepthFirstAstVisitor.cs
- ICSharpCode.Decompiler/CSharp/Syntax/FunctionPointerType.cs
- ICSharpCode.Decompiler/CSharp/Syntax/IAstVisitor.cs
- ICSharpCode.Decompiler/CSharp/Transforms/IntroduceUnsafeModifier.cs
- ICSharpCode.Decompiler/CSharp/TranslatedExpression.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/IL/ControlFlow/DetectPinnedRegions.cs
- ICSharpCode.Decompiler/IL/ILReader.cs
- ICSharpCode.Decompiler/IL/Instructions/CallIndirect.cs
- ICSharpCode.Decompiler/IL/PointerArithmeticOffset.cs
This PR improves the decompilation of C++/CLI and other IL code using features not directly available in C#.
The assembly from #2023 can be successfully decompiled + recompiled (at least when adding a reference to `System.Runtime.CompilerServices.Unsafe.dll`).
* Duplicate code where necessary in order to form well-structured pinned regions.
* Add support for decompiling `calli` (uses the proposed C# 9 syntax).
* Use `ref Unsafe.As<TFrom, TTo>(ref TFrom)` for ref-to-ref conversions.
* Use `Unsafe.AsPointer()` for conversions from managed references to unmanaged pointers.
> Improved decompilation of unsafe code

- ILSpy.Tests/ILSpy.Tests.csproj
- ILSpy/ILSpy.csproj
- ILSpy/Properties/app.config.template
Upgrade to newer SRM version on ILSpy *only*. This does not touch ICSharpCode.Decompiler (we have to keep SRM level with Roslyn there).
This is dogeared for vNext - we are too close to releasing v6.
> Upgrade ILSpy.exe to System.Reflection.Metadata 1.8.1

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/IL/Instructions/BlockContainer.cs
- ICSharpCode.Decompiler/IL/Instructions/ILFunction.cs
- ICSharpCode.Decompiler/IL/Instructions/ILInstruction.cs
- ICSharpCode.Decompiler/IL/Instructions/NullableInstructions.cs
- ICSharpCode.Decompiler/IL/Transforms/ILInlining.cs
- ICSharpCode.Decompiler/IL/Transforms/IndexRangeTransform.cs
This duplicate pass only made sense back when we ran CopyPropagation as part of the BlockILTransform.
> Remove redundant StatementTransform pass.

- .github/workflows/lock.yml
Uses https://github.com/marketplace/actions/lock-threads
Settings: issues only, run once a day, lock after 365 days, add comment why it was locked
Should we immediately go for 90 days as per https://github.com/icsharpcode/ILSpy/issues/1933#issuecomment-663998595?
> Lock closed issues after defined time period

- ILSpy/Metadata/CoffHeaderTreeNode.cs
- ILSpy/Metadata/OptionalHeaderTreeNode.cs
Fixes #2138 
Having the "Characteristics" lists in Metadata Explorer is great, but it would be even more helpful to see the individual values for each item in both lists. Doing so would make the relationship between the bit-masked value and the individual items that make up that value much clearer.
I added the flag value, wrapped in `<` and `>`, to the beginning (i.e. far left) of each "meaning".
_NOTE:_ I apologize that I have no ability to test this change. However, it should be extremely low-risk as I'm just adding some text to some strings.
&nbsp;
Take care,
Solomon...
https://SqlQuantumLeap.com/
> Fix #2138: Add flag values to both "Characteristics" lists in Metadata Explorer

- ILSpy/Metadata/OptionalHeaderTreeNode.cs
PE32+ images are reading 8 bytes (`UInt64`) for the "BaseOfData" field when they shouldn't be reading any bytes as this field is not present in PE32+ images (it's only found in PE32 images).
I ran across this issue because the DLL I'm checking just happens to be a PE32+ SQL Server DLL. If you're using Visual Studio and installed SQL Server Express LocalDB (or downloaded LocalDB separately), then you will have this DLL in the following location:
**C:\\Program Files\\Microsoft SQL Server\\{version_number}\\LocalDB\\Binn\\sqlaccess.dll**
If you have a regular / non-LocalDB edition of SQL Server, you will have this DLL in the following location:
**C:\\Program Files\\Microsoft SQL Server\\MSSQL{version}.{instance_name}\\MSSQL\\Binn\\sqlaccess.dll**
The problem is clearly evident in the current …
> Fix "Base of Data" for PE32Plus images in Optional Header (Metadata Explorer)

- ILSpy/Properties/Resources.zh-Hans.resx
Add translation for "DecompilerSettings.StringConcat" and other improvements.
翻译错误：
对空变量使用提升运算符 -> 对可为空类型使用提升运算符 https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/builtin-types/nullable-value-types
使用外部变量声明 -> 使用 out 变量声明 https://docs.microsoft.com/zh-cn/dotnet/csharp/whats-new/csharp-7#out-variables
对仅获取属性使用表达式内部成员语法 -> 对仅有 getter 访问器的属性使用 Expression-bodied 成员语法 https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members
尽可能贴合ms-docs：
字符串插值 -> 字符串内插
作为简单的文本值 -> 作为简单的字面值
在集合初始化器表达式中允许扩展 Add 方法 -> 允许使用 Add 扩展方法的集合初始化器表达式
与原有翻译风格一致：
反编译完成共耗时 {0:F1} 秒。-> 反编译完成。耗时 {0:F1} 秒。
> Update and improve Chinese translation

- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
This breaks build incrementality (fast up-to-date check) thinks XML Documentation.html is missing so it decides to rebuild the project every time, even if nothing has changed.
> Remove link to non-existing file.

- ICSharpCode.Decompiler.Console/IlspyCmdProgram.cs
When disassembling IL add a flag to enable showing sequence points. We
can already specify PDB loading; take advantage of that to provide
debug information for the decompiler.
When disassembling from the command line it isn't currently possible to see sequence
point information.
* When the `--il-sequence-points` flag is used the behavior is the same as
with `-il`, but sequence point information is aslo emitted. This leaves
things open to adding an `--il-metadata-tokens` flag too.
> Show Sequence Points from CLI

- ICSharpCode.Decompiler.Tests/CorrectnessTestRunner.cs
- ICSharpCode.Decompiler.Tests/Helpers/RoslynToolset.cs
- ICSharpCode.Decompiler.Tests/Helpers/Tester.VB.cs
- ICSharpCode.Decompiler.Tests/Helpers/Tester.cs
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Correctness/DeconstructionTests.cs
- ICSharpCode.Decompiler.Tests/TestCases/Correctness/NullableTests.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Issue1325.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/AutoProperties.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CompoundAssignmentTest.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/DeconstructionTests.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/DelegateConstruction.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/PropertiesAndEvents.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/VariableNaming.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/VariableNamingWithoutSymbols.cs
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/NoArrayInitializers.Expected.cs
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/NoArrayInitializers.opt.roslyn.il
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/NoArrayInitializers.roslyn.il
- ICSharpCode.Decompiler.Tests/UglyTestRunner.cs
- ICSharpCode.Decompiler.Tests/VBPrettyTestRunner.cs
- ICSharpCode.Decompiler/IL/Transforms/AssignVariableNames.cs
Fixes #2141 by downloading precompiled Roslyn compiler packages from https://www.nuget.org/packages/Microsoft.Net.Compilers. Note: these packages are marked as deprecated, we will have to switch to Microsoft.Net.Compilers.Toolset packages for newer versions of Roslyn.
Options we considered:
1) adding a separate tests project for each version of Roslyn we want to test with - con: increased complexity of our build is a problem
2) downloading different versions of Microsoft.CodeAnalysis.* packages and creating AppDomains (i.e. AssemblyLoadContext) for each version - con: Reflection and dynamic code is very awkward to work with. It would be necessary to create wrappers/copy enums to our code, etc.
3) using precompiled csc/vbc from Microsoft.Net.Compilers(.Toolset) packages - pro: simple …
> Run tests with different versions of Roslyn

- .github/workflows/build-ilspy.yml
- BuildTools/ghactions-install.ps1
Supports same build matrix as Azure DevOps (debug, release, store, ci). Current sample output: https://github.com/icsharpcode/ILSpy/actions/runs/352509460 (please verify contents of artifacts, esp. zip).
GH Packages push can only be verified on master because of if.
::set-output finally solved with code from https://github.com/mstum/Simplexcel/blob/master/.github/workflows/cibuild.yml
> GH Action build for ILSpy

- ICSharpCode.Decompiler/Metadata/DotNetCorePathFinder.cs
Loading Dlls from RemObjects caused:
```
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
bei ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder.DotNetCorePackageInfo..ctor(String fullName, String type, String path, String[] runtimeComponents)
bei ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder.<LoadPackageInfos>d__14.MoveNext()
bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
bei ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder..ctor(String parentAssemblyFileName, String targetFrameworkIdString, TargetFrameworkIdentifier targetFramework, Version targetFrameworkVersion, ReferenceLoadInfo loadInfo)
bei ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.FindAssemblyFile(IAssembl …
```
> ILSpy should not crash if fullName contains no "/" - no version info

- ICSharpCode.Decompiler/Humanizer/LICENSE
- ICSharpCode.Decompiler/Humanizer/Vocabularies.cs
- ICSharpCode.Decompiler/Humanizer/Vocabulary.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.nuspec.template
- ICSharpCode.Decompiler/IL/Transforms/AssignVariableNames.cs
- ILSpy/TreeNodes/BaseTypesTreeNode.cs
- packages.props
Fixes #2232: We only need a small percentage of features provided by Humanizer. Therefore we copy the relevant parts and remove the dependency in order to avoid such problems in the future.
> Remove Humanizer dependency

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunDisassembler.cs
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
A few major changes for ReadyToRun:
- Refactored the logic from `ReadyToRunLanguage` to a separate class `ReadyToRunDisassembler` to avoid excessive parameter passing.
- Updated `ILCompiler.Reflection.ReadyToRun` package,
- Avoid using `CountOfUnwindCodes`, that is just a lie,
- Added a stress mode so that these bugs can be detected more easily, not included in the build by default.
- Speed up `DecorateDebugInfo` significantly using an appropriately designed data structure. (The performance problem was found with the stress mode)
> r2r changes

- ILSpy/app.manifest
ILSpy uses the [`MessageBox`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.messagebox) class in a couple places. This is a [thin wrapper](https://github.com/dotnet/wpf/blob/d49f8ddb889b5717437d03caa04d7c56819c16aa/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/MessageBox.cs#L399) around the Win32 [`MessageBox`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox) function. Currently theming support is not enabled for the application, so these Win32 dialogs have the old Windows 2000 styling. By [turning on theming support in the manifest](https://docs.microsoft.com/en-us/windows/win32/sbscs/enabling-updated-common-controls-visual-styles-and-themes), the dialogs look slightly nicer.
> Enable theming for message boxes

- ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs
- ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs
- ICSharpCode.Decompiler/TypeSystem/DecompilerTypeSystem.cs
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
- ILSpy/Analyzers/AnalyzerScope.cs
- ILSpy/AssemblyList.cs
- ILSpy/AssemblyListManager.cs
- ILSpy/Languages/CSharpLanguage.cs
- ILSpy/Languages/ILLanguage.cs
- ILSpy/LoadedAssembly.cs
- ILSpy/LoadedAssemblyExtensions.cs
- ILSpy/LoadedPackage.cs
- ILSpy/MainWindow.xaml.cs
- ILSpy/TreeNodes/AssemblyListTreeNode.cs
- ILSpy/TreeNodes/AssemblyTreeNode.cs
- ILSpy/TreeNodes/ModuleReferenceTreeNode.cs
- ILSpy/ViewModels/ManageAssemblyListsViewModel.cs
I encountered a problem where sometimes the ILSpy UI freezes while decompiling a whole solution.
The issue was that the `lock (loadingAssemblies)` was held for too long (due to the blocking `GetPEFileOrNull()` calls inside the lock), and was also used on the UI thread (for the `App.Current.Dispatcher.BeginInvoke((Action)delegate () { ... lock (loadingAssemblies) { loadingAssemblies.Remove(file); }}`).
This PR eliminates the `loadingAssemblies` lock, instead handling multiple load requests for the same file within the `AssemblyList` itself.
It also changes the `DecompilerTypeSystem` to use the new `ResolveAsync` overload in order to parallelize the automatic assembly-loading.
Implementation changes:
* We no longer maintain the weird `loadingAssemblies` global state.
* `AssemblyList` now …
> async IAssemblyResolver

- ILSpy.BamlDecompiler/BamlConnectionId.cs
- ILSpy.BamlDecompiler/Handlers/Records/OptimizedStaticResourceHandler.cs
- ILSpy.BamlDecompiler/Handlers/Records/PropertyWithExtensionHandler.cs
- ILSpy.BamlDecompiler/Rewrite/ConnectionIdRewritePass.cs
MatchEventSetterCreation can't find EventSetter in followed cases:
```
example1:
<Style>
<EventSetter Event="MouseRightButtonDown" Handler="DataGridRow_OnMouseRightButtonDown" />
</Style>
ILFunction System.Windows.Markup.IStyleConnector.Connect {
param this : SmartQuant.WPF.Controls.Controller.StrategiesControl(Index=-1, LoadCount=1, AddressCount=0, StoreCount=1)
param connectionId : System.Int32(Index=0, LoadCount=1, AddressCount=0, StoreCount=1)
param target : System.Object(Index=1, LoadCount=1, AddressCount=0, StoreCount=1)
local eventSetter : System.Windows.EventSetter(Index=0, LoadCount=3, AddressCount=0, StoreCount=1)
BlockContainer {
Block IL_0000 (incoming: 1) {
if (comp.i4(ldloc connectionId == ldc.i4 6)) Block IL_0009 {
stloc eventSetter(newobj EventSetter..ctor())
callvirt …
```
> Fix baml decompiler can't find EventSetter

- ILSpy/Search/SearchPane.cs
When using "sort result by fitness", some results are not sorted in correct order.
* Fix insertion when result has to be inserted at the end (it was inserted at the second last position before)
> Fix insertion of result at end position

- ILSpy.BamlDecompiler/Rewrite/ConnectionIdRewritePass.cs
field assignment and event mapping can in the same block
see Block IL_00c3
```
Block IL_0000 (incoming: 1) {
BlockContainer (switch) {
Block IL_0007 (incoming: 1) {
switch (ldloc connectionId) {
case [long.MinValue..1),[21..long.MaxValue]: br IL_005c
case [1..2): br IL_0068
case [2..3): br IL_009b
case [3..4): br IL_00c3
case [4..5): br IL_00eb
case [5..6): br IL_00fc
case [6..7): br IL_010d
case [7..8): br IL_011e
case [8..9): br IL_012f
case [9..10): br IL_0140
case [10..11): br IL_0151
case [11..12): br IL_0162
case [12..13): br IL_017e
case [13..14): br IL_019a
case [14..15): br IL_01ab
case [15..16): br IL_01bc
case [16..17): br IL_01e1
case [17..18): br IL_0206
case [18..19): br IL_021f
case [19..20): br IL_0238
case [20..21): br IL_0251
}
}
Block IL_0251 (incoming: 1) {
stobj …
```
> Fix ConnectionIdRewritePass: field assignment and event mapping can in the same block

- ILSpy/ExtensionMethods.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/Search/SearchPane.cs
- ILSpy/Search/SearchResult.cs
Refactoring of the InsertResult method of the SearchPane to use BinarySearch in all cases for sorted insertion, as discussed in #2333
Also contains a small typo fix.
> Refactor searchresult insert

- ILSpy/Commands/SearchMsdnContextMenuEntry.cs
Before: https://docs.microsoft.com/dotnet/api/system.collections.generic.dictionary.keycollection..ctor
After: https://docs.microsoft.com/dotnet/api/system.collections.generic.dictionary-2.keycollection.-ctor
> Fix url of SearchMsdn when do search with generic types and .ctor methods

- ILSpy/LoadedAssembly.cs
Warning CS8625: Cannot convert null literal to non-nullable reference type.
Fix warning by making the parameter nullable.
> Fix warning CS8625

- ILSpy/ILSpy.csproj
- ILSpy/Metadata/Helpers.cs
- ILSpy/Options/DisplaySettingsPanel.xaml
- ILSpy/Options/OptionsDialog.xaml
- ILSpy/Options/OptionsDialog.xaml.cs
- ILSpy/themes/DarkTheme.xaml
- ILSpy/themes/LightTheme.xaml
- SharpTreeView/ICSharpCode.TreeView.csproj
@siegfriedpammer as requested in #2334
> Dark theme #665 fixes

- .gitignore
- ILSpy.BamlDecompiler/ILSpy.BamlDecompiler.csproj
- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy/App.xaml.cs
- ILSpy/ILSpy.csproj
- ILSpy/StorePackageHelper.cs
- SharpTreeView/ICSharpCode.TreeView.csproj
- global.json
- multitargeting.props.template
See issue #2324
To try: copy `multitargeting.props.template` to `multitargeting.props` and set `global.json/sdk/version` to `5.0.100`. Open VS, compile, select to run / edit for net5.0-windows.
Notes: the assembly resolution is very bare bones, it doesn't find localized assemblies in subfolders.
> Make it easy to play with .NET 5

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- NuGet.config
The change uses the `dotnet6-transport` feed to replace my personal feed to obtain `ILCompiler.Reflection.ReadyToRun.dll`.
> Switch to dotnet6-transport

- ICSharpCode.Decompiler/SingleFileBundle.cs
- ILSpy/LoadedPackage.cs
Adds support for the new version and also the new compressed files.
Reacts to .NET changes:
https://github.com/dotnet/runtime/pull/49855
https://github.com/dotnet/runtime/pull/50817
> Support for single-file bundle from .NET 6.

- ILSpy/AboutPage.cs
- ILSpy/App.xaml
- ILSpy/ILSpy.csproj
- ILSpy/ISmartTextOutput.cs
- ILSpy/MainWindow.xaml
- ILSpy/MainWindow.xaml.cs
- ILSpy/Options/DisplaySettings.cs
- ILSpy/Options/DisplaySettingsPanel.xaml
- ILSpy/Options/DisplaySettingsPanel.xaml.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/SessionSettings.cs
- ILSpy/TextView/DecompilerTextView.cs
- ILSpy/Themes/DarkTheme.xaml
- ILSpy/Themes/LightTheme.xaml
- ILSpy/Themes/ResourceKeys.cs
- ILSpy/Themes/ThemeManager.cs
- ILSpy/Themes/WindowStyleManagerBehavior.cs
- ILSpy/Themes/generic.xaml
- SharpTreeView/ICSharpCode.TreeView.csproj
Fixes #2409: 
If you like to have the title bar styled along with the theme you can now opt via View-Options-Display. 
Default is no styling.
It also fixes the border color mentioned in #2359
> Fix #2409: Styling of windows title bar is now optional.

- ICSharpCode.Decompiler/Disassembler/DisassemblerHelpers.cs
Decompiling of assembly containing a identifier with two dots result of il that is not valid by ilasm.exe.
Test code used [test.zip](https://github.com/icsharpcode/ILSpy/files/6409584/test.zip).
```
ilasm.exe /DLL .\test_decompiled.il
```
```
.\test_decompiled.il(28) : error : syntax error at token '.' in:        .field private static int32 foo..bar
```
Add quotes to any identifier that contains repeating dots (i.e. "..").
> Fix invalid il from identifiers containing repeating dots

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExceptionHandling.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Loops.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ReduceNesting.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/IL/ControlFlow/ConditionDetection.cs
- ICSharpCode.Decompiler/IL/ControlFlow/ExitPoints.cs
- ICSharpCode.Decompiler/IL/ControlFlow/RemoveRedundantReturn.cs
- ICSharpCode.Decompiler/IL/Instructions/InstructionCollection.cs
- ICSharpCode.Decompiler/IL/Instructions/Leave.cs
- ICSharpCode.Decompiler/IL/Transforms/HighLevelLoopTransform.cs
- ICSharpCode.Decompiler/IL/Transforms/ReduceNestingTransform.cs
- ILSpy/LoadedAssembly.cs
Only transform to fall-through block-exit at the end of the transform pipeline.
This fixes an issue where `return` statements within try-blocks could turn into `goto` statements (#2379).
> Fix #2379: Keep `return` statements around in original form for ConditionDetection

- ILSpy/ILSpy.csproj
- ILSpy/LoadedAssembly.cs
- doc/third-party-notices.txt
Fixes #2137.
Assemblies included in mobile Android apps created with Xamarin can be compressed. This PR detects compressed assemblies and attempts to decompress them in order to correctly load the assembly. This is handy when analyzing mobile apps created with Xamarin using ILSpy.
* Extend class ``LoadedAssembly`` to detect and load compressed Xamarin assemblies if direct loading of assembly fails.
* Requires Nuget pkg K4os.Compression.LZ4 for LZ4 decompression.
> Support loading compressed Xamarin assemblies, see #2137

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunDisassembler.cs
This change updates the `ILCompiler.Reflection.ReadyToRun` version that so it can disassemble the ready to run binaries generated by .NET 6. The version is tested under the `STRESS` mode [here](https://github.com/icsharpcode/ILSpy/blob/dd1621a811459da26b8fc2d993ec50c2f2b50704/ILSpy.ReadyToRun/ReadyToRunLanguage.cs#L19) and the test passed.
I have to turn off the assertion because of https://github.com/dotnet/runtime/issues/47202. It was fine because `USING_VARIABLE_LIVE_RANGE` was off, but now it is on after https://github.com/dotnet/runtime/pull/50162.
> Update ready to run

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CovariantReturns.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/KnownAttributes.cs
Adds support for C# 9 covariant return types in methods and getter-only properties and indexers.
> C# 9 Covariant Returns

- ILSpy/Analyzers/AnalyzerScope.cs
Scenario:
- Load `System` assembly together with e.g. unknown assembly which IL Spy cannot read (so it shows error in a tree)
- Find any attribute and Analyze it
- In the Analysis window expand "Applied To" analysis.
The following error occurs:
The `AnalyzerScope.GetAllModules()` was not expected to return `null` modules as I can see by the usages around. So I fixed that by filtering out invalid modules from Assembly List
> Fix attribute application analysis could fail if there are wrong assemblies loaded

- ILSpy.BamlDecompiler/BamlDecompilerTypeSystem.cs
Fix CS8073: `The result of the expression is always 'true' since a value of type 'TypeDefinitionHandle' is never equal to 'null' of type 'TypeDefinitionHandle?'`
`TypeDefinitionHandle` is an struct and can never be null.
> Fix null check in BamlDecompilerTypeSystem.HasType

- ILSpy/FilterSettings.cs
https://github.com/icsharpcode/ILSpy/issues/2493
It is hard to filter the nodes by a single term, Search should be at least extensible
The solution is a semi-hack, since in future class extensions the member `SearchTerm` may or may not be used, but I consider to be the easiest solution that opens the class to extensions
> #2493 make SearchTermMatches virtual for possible FilterSettings extensions

- ILSpy.BamlDecompiler.Tests/BamlTestRunner.cs
- ILSpy.BamlDecompiler.Tests/Cases/Issue2116.xaml
- ILSpy.BamlDecompiler.Tests/Cases/Issue2116.xaml.cs
- ILSpy.BamlDecompiler.Tests/ILSpy.BamlDecompiler.Tests.csproj
- ILSpy.BamlDecompiler/Handlers/Records/PropertyWithExtensionHandler.cs
https://github.com/icsharpcode/ILSpy/issues/2116
issue https://github.com/icsharpcode/ILSpy/issues/2116 and another old pr https://github.com/icsharpcode/ILSpy/pull/2229
this also fixes missing x:Type
before:
after:
> Fix missing x:Static and x:Type in decompiled BAML

- .github/workflows/build-frontends.yml
- .github/workflows/build-ilspy.yml
- .github/workflows/codeql-analysis.yml
- ICSharpCode.Decompiler.Console/ICSharpCode.Decompiler.Console.csproj
- ICSharpCode.Decompiler.Tests/Helpers/Tester.cs
- README.md
- global.json
- multitargeting.props.template
ILSpy is currently using  the .NET 5.0 SDK. It will be end of support by May 8th, 2022 (see https://dotnet.microsoft.com/platform/support/policy/dotnet-core)
.NET 6 is an LTS release with EOL of November 08, 2024 (one year beyond .NET 8.0). .NET 6 also fixes a bunch of issues for ARM64 platforms, which comes in handy for testing via multitargeting.props.
> Switch to using the .NET 6.0 SDK

- ICSharpCode.Decompiler.Tests/TestTraceListener.cs
- ILSpy/ILSpyTraceListener.cs
They are the same thing, and the latter one is available for net6.0
> Use Trace.Listeners instead of Debug.Listeners

- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/ForLoopTests.xml
- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/HelloWorld.xml
- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/LambdaCapturing.xml
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs
- ICSharpCode.Decompiler/DebugInfo/PortablePdbWriter.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ILSpy/Commands/ExtractPackageEntryContextMenuEntry.cs
- ILSpy/Commands/GeneratePdbContextMenuEntry.cs
- ILSpy/Commands/SelectPdbContextMenuEntry.cs
- ILSpy/Options/MiscSettingsPanel.xaml
- ILSpy/Options/MiscSettingsPanel.xaml.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/TextView/DecompilerTextView.cs
- ILSpy/TreeNodes/AssemblyTreeNode.cs
- ILSpy/TreeNodes/ResourceNodes/ResourceEntryNode.cs
- ILSpy/TreeNodes/ResourceNodes/ResourceTreeNode.cs
- ILSpy/TreeNodes/ResourceNodes/ResourcesFileTreeNode.cs
- Replace DecompilerTextView.CleanUpName with direct uses of WholeProjectDecompiler.CleanUpFileName.
- Add file extension handling to WholeProjectDecompiler.CleanUpName
- Add WholeProjectDecompiler.SanitizeFileName, which respects file extensions.
> Improve file name sanitizer

- ILSpy/Commands/CopyFullyQualifiedNameContextMenuEntry.cs
- ILSpy/Commands/ScopeSearchToAssembly.cs
- ILSpy/Commands/ScopeSearchToNamespace.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/Search/AbstractEntitySearchStrategy.cs
- ILSpy/Search/AbstractSearchStrategy.cs
- ILSpy/Search/AssemblySearchStrategy.cs
- ILSpy/Search/LiteralSearchStrategy.cs
- ILSpy/Search/MemberSearchStrategy.cs
- ILSpy/Search/MetadataTokenSearchStrategy.cs
- ILSpy/Search/NamespaceSearchStrategy.cs
- ILSpy/Search/ResourceSearchStrategy.cs
- ILSpy/Search/SearchPane.cs
Implements features requested in #828 and #1175:
* `innamespace:` and `inassembly:` predicates in the search text box
* "scope to this namespace/assembly" command for tree nodes and search results, allowing to generate `innamespace:` and `inassembly:` predicates
> Search predicates

- ICSharpCode.Decompiler/DebugInfo/KnownGuids.cs
- ILSpy/Metadata/DebugTables/CustomDebugInformationTableTreeNode.cs
For .NET 6/C# 10 we added a new CustomDebugInformation type for linking a TypeDef entry to a Document entry, in https://github.com/dotnet/roslyn/pull/56278
This updates ILSpy to correctly display the information.
Before:
After:
The `02` in the value is correct, it refers to the 2nd row of the Document table.
Sorry I took so long to submit this PR :)
> Add TypeDefinitionDocuments to custom debug information data

- ILSpy/TreeNodes/ResourceNodes/IconResourceEntryNode.cs
When `BitmapCacheOption.None` is used, icons will not be loaded from the
stream until they are needed to be displayed. In this case, the icon
loading will be triggered when the text box is rendered from the UI thread.
However by that time the steam object will have already been disposed.
This results in no icons being visible.
The fix is to eager load the icons while the stream is still alive.
An alternative fix would be to defer disposing the stream to a later time
or not dispose it at all.
> Fix displaying icons from embedded resources

- ILSpy/AboutPage.cs
- ILSpy/Commands/CheckForUpdatesCommand.cs
- ILSpy/Commands/DecompileAllCommand.cs
- ILSpy/Commands/DisassembleAllCommand.cs
- ILSpy/Commands/ExitCommand.cs
- ILSpy/Commands/ExportCommandAttribute.cs
- ILSpy/Commands/GeneratePdbContextMenuEntry.cs
- ILSpy/Commands/ManageAssemblyListsCommand.cs
- ILSpy/Commands/OpenCommand.cs
- ILSpy/Commands/OpenFromGacCommand.cs
- ILSpy/Commands/Pdb2XmlCommand.cs
- ILSpy/Commands/RefreshCommand.cs
- ILSpy/Commands/RemoveAssembliesWithLoadErrors.cs
- ILSpy/Commands/SaveCommand.cs
- ILSpy/Commands/SortAssemblyListCommand.cs
- ILSpy/ContextMenuEntry.cs
- ILSpy/Docking/CloseAllDocumentsCommand.cs
- ILSpy/ExtensionMethods.cs
- ILSpy/MainWindow.xaml
- ILSpy/MainWindow.xaml.cs
- ILSpy/Options/OptionsDialog.xaml.cs
- TestPlugin/MainMenuCommand.cs
See #2605 and #2604
I added one resp. two new properties to our main menu/context menu attributes:
Main menus now can define IDs, which should be unique across the whole application. And by using the already existing Menu property, the submenu item can be connected to its parent item.
Context menus can do the same:
Examples:
// Adds a sub menu to the file menu
[ExportMainMenuCommand(Menu = "_File", Header = "Sub Menu", ID = "SubMenuParent")]
sealed class DummyMenuItem
{
}
[ExportMainMenuCommand(Menu = "SubMenuParent", Header = "SubItem")]
sealed class TestCommand : SimpleCommand
{
public override void Execute(object parameter)
{
throw new NotImplementedException();
}
}
// Adds a sub menu to all context menus
[ExportContextMenuEntry(Header = "Sub Menu", ID = "SubMenuParent")]
sealed class …
> Submenu support

- ICSharpCode.Decompiler.Console/IlspyCmdProgram.cs
New `--nested-directories` flag in ilspycmd that allows to use the decompiler setting `UseNestedDirectoriesForNamespaces`
https://github.com/icsharpcode/ILSpy/issues/2635
> ilspycmd nested directories decompiler setting

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/IL/Transforms/LocalFunctionDecompiler.cs
- ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs
- ICSharpCode.Decompiler/Metadata/FindTypeDecoder.cs
- ICSharpCode.Decompiler/Metadata/MetadataExtensions.cs
- ICSharpCode.Decompiler/Metadata/PEFile.cs
- ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs
- ICSharpCode.Decompiler/SRMExtensions.cs
- ICSharpCode.Decompiler/TypeSystem/ITypeDefinition.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataTypeDefinition.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MinimalCorlib.cs
- ILSpy/Analyzers/AnalyzerContext.cs
- ILSpy/Analyzers/AnalyzerHelpers.cs
- ILSpy/Analyzers/AnalyzerScope.cs
- ILSpy/Analyzers/AnalyzerSearchTreeNode.cs
- ILSpy/Analyzers/Builtin/AttributeAppliedToAnalyzer.cs
- ILSpy/Analyzers/Builtin/FindTypeInAttributeDecoder.cs
- ILSpy/Analyzers/Builtin/MethodUsedByAnalyzer.cs
- ILSpy/Analyzers/Builtin/TypeUsedByAnalyzer.cs
- ILSpy/AssemblyList.cs
- ILSpy/AssemblyListSnapshot.cs
- ILSpy/Languages/Language.cs
- ILSpy/LoadedAssembly.cs
- ILSpy/LoadedAssemblyExtensions.cs
This is the result of our efforts to improve the speed of our built-in analyzers. See also #2594.
> Analyzer optimization

- ICSharpCode.Decompiler.Tests/CorrectnessTestRunner.cs
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/TestCases/Correctness/ComInterop.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
… This was resulting in fatal crashes while running decompiled COM interop code.
#2638
See #2638 for more details on the problem being solved
* I have factored out the problem of determining whether native member ordering is required into its own function. If it's not required, ILSpy will still group the members by kind (fields, properties, methods, events).
* Added a new correctness unit test that validates COM V-table ordering does not change across a decompile loop
> Fix the ordering of COM interface methods, properties, and events to appear in their originally defined order

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/Transforms/PatternStatementTransform.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/KnownAttributes.cs
- ICSharpCode.Decompiler/Util/MultiDictionary.cs
Fixes #1607: The static methods are no longer removed from the decompiled output.
> Keep compiler-generated code that is still referenced

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PdbGenerationTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/CustomPdbId.xml
- ICSharpCode.Decompiler/DebugInfo/PortablePdbWriter.cs
The Visual Studio debugger's decompiler integration needs to be able to control the ID used for generated PDBs.  There are a couple of scenarios that are interesting to us:
1. Generating a PDB for an assembly that was built without debug info. The PDB writer currently fails in this case, since the input assembly has no debug directory from which to extract the relevant info.  The debugger can provide values that will allow us to load the generated PDB.
2. Generating a PDB for an assembly that has multiple debug directories.  The PDB writer currently uses the first debug directory it finds, but this isn't necessarily the correct one.  The debugger can disambiguate these and provide the correct values.
This commit adds a new parameter to `PortablePdbWriter.WritePdb` that allows the caller …
> Allow user to provide ID when generating a PDB

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/ILPrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/GuessAccessors.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/GuessAccessors.il
- ICSharpCode.Decompiler/TypeSystem/Implementation/FakeMember.cs
- ICSharpCode.Decompiler/TypeSystem/MetadataModule.cs
- ILSpy/Analyzers/Builtin/MemberImplementsInterfaceAnalyzer.cs
- ILSpy/Analyzers/Builtin/MethodUsedByAnalyzer.cs
eg. decompile to `.Property` instead of `.get_Property()`
Two assemblies:
``` csharp 
using System;
namespace UnknownNamespace
{
public class UnknownClass<T>
{
public T UnknownProperty { get; set; }
public event EventHandler<T> OnEvent;
public T this[T index]
{
get => default;
set { }
}
public T this[T x, T y]
{
get => default;
set { }
}
}
}
```
And
``` csharp
using System;
namespace ClassLibrary1
{
public class Class1 : EventArgs
{
public void Method()
{
var instance = new UnknownNamespace.UnknownClass<Class1>();
var valueOfProp = instance.UnknownProperty;
instance.UnknownProperty = valueOfProp;
instance.OnEvent += Instance_OnEvent;
instance.OnEvent -= Instance_OnEvent;
var valueOfIndexer = instance[this];
instance[this] = valueOfIndexer;
var valueOfMultiIndexer = instance[this, this]; …
```
> Assume conventionally named unresolved method references are properties or events

- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/TargetServices.cs
When C++/CLI project produce assembly it generates target attribute like this
```
[assembly: TargetFramework(".NETCoreApp,Version=7.0", FrameworkDisplayName = "")]
```
when C# generates `TargetFrameworkAttribute` it produce slightly different format
```
[assembly: TargetFramework(".NETCoreApp,Version=v7.0", FrameworkDisplayName = "")]
```
Link to, or brief information about the issue
> Allow decompile C++/CLI assemblies

- ICSharpCode.Decompiler/IL/Transforms/TransformArrayInitializers.cs
- ICSharpCode.Decompiler/Util/CollectionExtensions.cs
N/A
The TransformArrayInitializers allocates a lot of unnecessary arrays.
`DecodeArrayInitializer` - Instead of relying on the Add method of a list to expand the underlying array when necessary, the code now allocates a big enough array to fit all the elements removing the need for the Add method to expand the array several times.
`BlockFromInitializer` now reuses a single instance of List<ILInstruction> instead of reallocating a new one every time and clears it when necessary. The same pre-allocation approach mentioned above has been implemented here too.
> Reduce allocations in TransformArrayInitializers

- .github/workflows/build-ilspy.yml
We need to lock in a specific version of dotnet format and not use the one coming with the SDK - so we tap the AzDO feed and install a specific version that is then called "dotnet-format". This is similar to before but there are no longer versions published on nuget.org. Like in https://github.com/dotnet/format/issues/1641, we also to have a common version everywhere.
> Install specific version of dotnet-format from AzDO feed

- ILSpy.BamlDecompiler.Tests/ILSpy.BamlDecompiler.Tests.csproj
- ILSpy.BamlDecompiler/ILSpy.BamlDecompiler.csproj
- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy/ILSpy.csproj
- SharpTreeView/ICSharpCode.TreeView.csproj
- TestPlugin/TestPlugin.csproj
On non-Windows platforms, this property eliminates a slew of invalid errors, ranging from being unable to find standard classes, when refactoring source files belonging to csprojs targeting .NET 6 on Windows.
> Add EnableWindowsTargeting propery to csprojs targeting net6.0-windows

- ILSpy.AddIn.VS2022/ILSpy.AddIn.VS2022.csproj
- ILSpy.AddIn/ILSpy.AddIn.csproj
Update https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools to 7.3.2093 to match https://github.com/actions/runner-images/blob/af3dd14fe039b539ac16336e571f761173676b3e/images/win/Windows2022-Readme.md 
Matching VS Build number to version: https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?preserve-view=true&view=vs-2022
Now both projects need latest VSSDK.
> Use latest VS SDK

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/Resolver/CSharpOperators.cs
- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ICSharpCode.Decompiler/TypeSystem/ComHelper.cs
- ICSharpCode.Decompiler/TypeSystem/IEntity.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/AttributeListBuilder.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/FakeMember.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/KnownAttributes.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/LocalFunctionMethod.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataEvent.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataField.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataMethod.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataProperty.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataTypeDefinition.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MinimalCorlib.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/SpecializedMember.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/SyntheticRangeIndexer.cs
- ICSharpCode.Decompiler/TypeSystem/InheritanceHelper.cs
- ICSharpCode.Decompiler/TypeSystem/TypeSystemExtensions.cs
- ICSharpCode.Decompiler/TypeSystem/VarArgInstanceMethod.cs
- ILSpy/Analyzers/Builtin/AttributeAppliedToAnalyzer.cs
See #1204
Time spent in `AddDefinesForConditionalAttributes` is reduced from 136ms to 60ms. For the overall decompilation time this is not a significant change.
> Add optimized implementation of HasAttribute and GetAttribute to IEntity.

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ICSharpCode.Decompiler/CSharp/Transforms/IntroduceUsingDeclarations.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ILSpy/ILSpy.csproj
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
N/A
There is no option to always fully qualify type names to the strongest extent: even AlwaysQualifyMemberReferences | !UsingDeclarations omits the use of global::. This can be a problem when dealing with name confusion such as in [this SO answer](https://stackoverflow.com/a/72318963). I haven't been able to quickly generate a repro case, but anecdotally, using this option has resolved a number of cases in which the ILSpy generated code will not compile. In general, when compilability of generated code is a goal, this option seems like it would be handy to have.
Of note is that StringInterpolation will probably need to be set to false when this option is enabled, as the C# compiler confuses the colon in "global::" for a formatting specifier. Perhaps it's …
> Add option to always fully qualify type names with global::

- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
ICS.D is used downstream with specific package version requirements. ILSpy can use newer version. Currently both share the packages.props file and that way ICS.D could inadvertently pick up a newer version it shouldn't (eg via #2774)
To avoid that issue simply use fixed versions in the csproj and only let the rest of ILSpy pick up from packages.props.
> Do not use packages.props for ICS.D.csproj

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
- NuGet.config
- packages.props
This change updates the `ILCompiler.Reflection.ReadyToRun.Experimental` package to a newer version to be compatible with .NET 7.
> Refresh ready to run for .NET 7

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/Disassembler/ILParser.cs
- ICSharpCode.Decompiler/Disassembler/MethodBodyDisassembler.cs
- ICSharpCode.Decompiler/IL/BlockBuilder.cs
- ICSharpCode.Decompiler/IL/ControlFlow/AsyncAwaitDecompiler.cs
- ICSharpCode.Decompiler/IL/ILReader.cs
- ICSharpCode.Decompiler/IL/Transforms/ILInlining.cs
This is a performance optimization: we dramatically reduce the amount of ILVariables created;
and thus need to spend less time in the first ILInlining run.
> Optimize ILReader: don't create stack slots if we can directly created inlined ILAst

- ICSharpCode.Decompiler/CSharp/Resolver/CSharpResolver.cs
https://github.com/icsharpcode/ILSpy/issues/2736
CSharpResolver had a bug that would result in it returning an inaccessible type.
* Check if the type is accessible before returning it.
fixes #2736
> Implement a fix for #2736

- ICSharpCode.Decompiler.PowerShell/GetDecompiledProjectCmdlet.cs
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PdbGenerationTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/CustomPdbId.xml
- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/ProgressReporting.xml
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs
- ICSharpCode.Decompiler/DebugInfo/PortablePdbWriter.cs
- ICSharpCode.Decompiler/DecompilationProgress.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ILSpy/Commands/GeneratePdbContextMenuEntry.cs
- ILSpy/DecompilationOptions.cs
- ILSpy/Languages/CSharpLanguage.cs
- ILSpy/MainWindow.xaml.cs
- ILSpy/TextView/DecompilerTextView.cs
- ILSpy/TextView/DecompilerTextView.xaml
As discussed in #2801, the Visual Studio debugger would like to be able to provide better progress feedback to users while a decompilation operation is in progress.
This commit adds a new parameter to `PortablePdbWriter.WritePdb` that allows the caller to provide an implementation of `IProgress<>` to receive status updates on the pdb generation process.  Currently, the progress reports include the number of files generated so far and the total number of files.
#2801 mentions adding progress reporting to `WholeProjectDecompiler` as well, but that appears to already be present - see: https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs#L256
> Add progress reporting to PortablePdbWriter

- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/GuessAccessors.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/GuessAccessors.il
- ICSharpCode.Decompiler/CSharp/CallBuilder.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/FakeMember.cs
- ICSharpCode.Decompiler/TypeSystem/MetadataModule.cs
ILSpy crashed with NullReferenceException when it couldn't resolve some dependency (Newtonsoft.Json in my case, the problem was around `JObject.Item[string]` indexer)
Seems like a typo when FakeProperty is initialized - the setter method was assigned to the Getter property
First commit contains the actual fix.
In the second commit I included some asserts and a ToString implementation I used to debug the problem. I'm guessing that more asserts would be welcome, but if you don't like it, just merge only the first commit.
- Sorry, but I couldn't make the tests run on Linux, is there any way?
- I also don't know how to replicate this problem in unit tests - I'd have to compile a dll against some library which the decompiler won't see at runtime.
> Fix initialization of FakeProperty with setter 

- ILSpy/Languages/CSharpLanguage.cs
When exploring decompiled methods and other members and jumping all around through analysis tree, inheritance etc., it is difficult to figure out to which assembly the currently displayed code belongs. On has to scroll the treeview to an exact narrow position, or just keep collapsing it manually.
The proposed solution is to include the assembly name as a comment above the existing comment containing full type name.
Another approach would be to include it with the type comment in `CSharpAmbience.ConvertSymbol`, possibly using `ConversionFlags.UseAssemblyName`, but that seemed unnecessarily complex.
Namespaces do not show assembly because it is not readily available around.
This does not come with tests, happy to add some if deemed necessary and given some pointers whereabouts are similar …
> Include assembly name in decompiled code

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Records.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/StaticAbstractInterfaceMembers.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Structs.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/Syntax/CSharpModifierToken.cs
- ICSharpCode.Decompiler/CSharp/Syntax/Modifiers.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/KnownAttributes.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
Implements support for C# 11 required members.
Also adds another test for static abstract interface members.
> C# 11: Required members

- ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs
https://github.com/icsharpcode/ILSpy/issues/2842
The `ZennoLab.Structures.Properties.Resources` class contained a property that had it's return type set to `System.Globalization.CultureInfo` but the accessor parameters used `System.Object`. This caused the `RequiredNamespaceCollector` not to detect the `System.Globalization` namespace. This led to the assertion mentioned in the issue.
Include return types of properties and events in the analysis done by `RequiredNamespaceCollector`.
fixes #2842
> Include property and event return types in `RequiredNamespaceCollector`

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/TestCases/VBPretty/VBAutomaticEvents.cs
- ICSharpCode.Decompiler.Tests/TestCases/VBPretty/VBAutomaticEvents.vb
- ICSharpCode.Decompiler.Tests/VBPrettyTestRunner.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/Transforms/PatternStatementTransform.cs
N/A
ILSpy did not properly support automatic events generated by the Visual Basic compiler. The backing field naming convention used by the Visual Basic compiler is different than the one used by the C# one. Instead of the field having the same name as the event, it uses the events name and appends the `Event` suffix to it. This different naming convention caused ILSpy to fail to detect automatic events and the decompiled code was very messy.
Before:
```csharp
public class VBAutomaticEvents
{
public delegate void EventWithParameterEventHandler(int EventNumber);
public delegate void EventWithoutParameterEventHandler();
[CompilerGenerated]
private EventWithParameterEventHandler EventWithParameterEvent;
[CompilerGenerated]
private …
```
> Add support for VB.NET automatic events

- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/Semantics/OverloadResolutionTests.cs
N/A
The ICSharpCode.Decompiler.Tests project contained a few tests that were marked to be ignored due to them being broken when in reality they pass without any issues!
* Re-enable said tests
> Enable tests which no longer fail

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/YieldReturn.cs
- ICSharpCode.Decompiler/IL/Transforms/LockTransform.cs
N/A
ILSpy did not properly decompile `lock` statements in yield return state machines generated by the legacy C# compiler. This was due to a variation in the ILAst pattern. The difference is an extra variable.
Before changes:
```csharp
public static IEnumerable<int> YieldReturnInLock1(object o)
{
bool lockTaken = false;
object obj2 = default(object);
try
{
object obj;
obj2 = (obj = o);
Monitor.Enter(obj, ref lockTaken);
yield return 1;
}
finally
{
if (lockTaken)
{
Monitor.Exit(obj2);
}
}
}
```
After changes:
```csharp
public static IEnumerable<int> YieldReturnInLock1(object o)
{
lock (o)
{
yield return 1;
}
}
```
* Added support for the ILAst pattern mentioned above
* Enabled the previously disabled test cases for `lock` statements in yield return state …
> Add support for `lock` statements within yield return state machines

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/DynamicTests.cs
- ICSharpCode.Decompiler/TypeSystem/ApplyAttributeTypeVisitor.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataField.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataMethod.cs
N/A
ILSpy did not correctly decompile `volatile dynamic` fields.
Example:
```csharp
static volatile dynamic volatileField;
```
would decompile to:
```csharp
static volatile object volatileField;
```
The issue lies in the implementation of `ApplyAttributeTypeVisitor`. This class did not properly handle modifier signatures (`CModOpt` and `CModReqd`) which are used to indicate that a field is volatile.
Roslyn implementation: https://github.com/dotnet/roslyn/blob/29cdbf9a70ae83e6b7b914182fc78a7ed122a0a0/src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs#L850
Modifier signatures are now correctly handled. The `dynamicTypeIndex` is incremented for every modifier type to match Roslyn's behavior when it generates the `DynamicAttribute` attributes. …
> Fix dynamic type index calculation in `ApplyAttributeTypeVisitor`

- ICSharpCode.Decompiler.Tests/CorrectnessTestRunner.cs
Follow up to https://github.com/icsharpcode/ILSpy/pull/2852. I missed the MiniJSON test when re-evaluating the tests which were marked as `Ignore`.
> Enable MiniJSON test for MCS 2.6.4

- ICSharpCode.Decompiler/IL/Transforms/CachedDelegateInitialization.cs
https://github.com/icsharpcode/ILSpy/issues/2199
The `CachedDelegateInitialization` transform did not fully support VB cached delegate initialization. The pattern emitted when an anonymous function uses a local from a display class/closure was not supported. This can be seen by decompiling `Class5.method_0()` from the sample provided in the aforementioned issue report. This can be seen in the code inside the first try region.
Before:
```csharp
private void method_0(ClassHttpRequest classHttpRequest_0, string string_0)
{
string text = "";
if (!bool_1)
{
text = "請先進行登入認證~";
return;
}
ClassHttpRequest val = classHttpRequest_0;
_Closure$__35-0 arg = new _Closure$__35-0(arg);
arg.$VB$Local_totp_code = "";
arg.$VB$Local_frm = new Form();
Form $VB$Local_frm = …
```
> Add support for VB.NET cached delegate initialization with closures

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/TestCases/VBPretty/VBNonGenericForEach.cs
- ICSharpCode.Decompiler.Tests/TestCases/VBPretty/VBNonGenericForEach.vb
- ICSharpCode.Decompiler.Tests/VBPrettyTestRunner.cs
- ICSharpCode.Decompiler/IL/Transforms/UsingTransform.cs
https://github.com/icsharpcode/ILSpy/issues/2199
The file present in the issue contained a strange variation of a using statement with the `isinst`. I am unsure what compiler is responsible for this kind of IL. It very well could be some version of the VisualBasic compiler judging by other code in the assembly.
An example of this can be found in `Class8.smethod_0()`.
Before:
```csharp
public static void smethod_0()
{
_Closure$__4-0 arg = default(_Closure$__4-0);
_Closure$__4-0 CS$<>8__locals0 = new _Closure$__4-0(arg);
if (Program.bool_0 || DateTime.Compare(dateTime_0, DateAndTime.Now.AddMinutes(-5.0)) > 0)
{
return;
}
dateTime_0 = DateAndTime.Now;
CS$<>8__locals0.$VB$Local_listhost = new List<string>();
List<string> $VB$Local_listhost = …
```
> Fix `UsingTranform` for inlined `isinst` variation (refs #2199)

- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/IProjectFileWriter.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/ProjectFileWriterDefault.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/ProjectFileWriterSdkStyle.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs
- ILSpy.BamlDecompiler/BamlResourceNodeFactory.cs
- ILSpy/Languages/CSharpLanguage.cs
- ILSpy/Languages/IResourceFileHandler.cs
* Fixes #2830 
* Fixes #2850 
* Introduce `LogicalName` property for resources
* Emit additional properties for XAML files
> Improve WholeProjectDecompiler

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CompoundAssignmentTest.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformAssignment.cs
https://github.com/icsharpcode/ILSpy/issues/2620 (This PR only partially resolves this issue)
ILSpy did not properly handle post-increment and post-decrement on pointers for other pointer types than `byte*`
* Extend pattern-matching logic to support more post-increment and post-decrement cases
* Re-enabled a previously disabled test in `CompoundAssignmentTest` pretty test which tests this newly added behavior.
> Improve support for post-increment/decrement on pointers

- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpAmbience.cs
Fixes #2910
`CSharpAmbience` did not support record structs.
* Add support for record structs to `CSharpAmbience` basing the new code on `CSharpOutputVisitor`
> Add support for record structs in `CSharpAmbience` (fixes #2910)

- ICSharpCode.Decompiler/Util/ResXResourceWriter.cs
N/A
In newer runtime versions, MemoryStream is no longer a serializable type like it was in .NET Framework. This leads to an exception when exporting an assembly with resources using a resource element of the `Stream` type code.
* Implement explicit support for the `MemoryStream` class instantiated by `ResourcesFile`.
> Fix `ResXResourceWriter` support for `MemoryStream` resource element

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
Fixes #2908
Obfuscated IL code to lead to delegate declarations with empty parameter names being produced.
* Replace the empty parameter names with default parameter names following the naming convention used by ILReader.
> Fix empty parameter names in delegate declarations (fixes #2908)

- .gitignore
- ICSharpCode.Decompiler.Tests/DisassemblerPrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/TestCases/Disassembler/Pretty/InterfaceImplAttributes.il
- ICSharpCode.Decompiler/Disassembler/ReflectionDisassembler.cs
- ILSpy/TextView/ILAsm-Mode-Dark.xshd
- ILSpy/TextView/ILAsm-Mode.xshd
I noticed the following output when decompiling an assembly:
That `implements .custom` part seemed wrong, and indeed, `ildasm` uses another syntax instead: `.interfaceimpl type` ([see here](https://github.com/dotnet/runtime/blob/7908e8ef62c7d5ebdcd6459faccd755b9b10d369/src/coreclr/ildasm/dasm.cpp#L4847-L4870)).
Here is the result:
This PR moves the custom attributes on interface implementations inside the type body and adds one `.interfaceimpl type` declaration for each interface implementation which has a custom attribute.
While implementing this, I noticed that `ilasm` is inconsistent with `ildasm` when multiple attributes are applied to an …
> Use `.interfaceimpl type` syntax

- ILSpy/Commands/ILSpyCommands.cs
- ILSpy/Commands/SetThemeCommand.cs
- ILSpy/MainWindow.xaml
- ILSpy/Options/DisplaySettingsPanel.xaml
- ILSpy/Options/DisplaySettingsPanel.xaml.cs
- ILSpy/Options/DisplaySettingsViewModel.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/SessionSettings.cs
Closes #2929 
The theme selector combobox in the toolbar seems out of place.
This replaces the theme selector in the toolbar with a menu item and a setting in the options:
The theme is currently saved in the `SessionSettings`, and this PR doesn't change that. But this leads to updating the `SessionSettings` from the `DisplaySettings` panel.
An alternative would be to move the theme to `DisplaySettings`, but that would require updating it when switching the theme from the main menu and saving it on exit just like the `SessionSettings`, so I'm not sure if that would be better in the end.
> Change theme selection UI

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/TestCases/VBPretty/YieldReturn.cs
- ICSharpCode.Decompiler.Tests/TestCases/VBPretty/YieldReturn.vb
- ICSharpCode.Decompiler.Tests/VBPrettyTestRunner.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/IL/ControlFlow/StateRangeAnalysis.cs
- ICSharpCode.Decompiler/IL/ControlFlow/SymbolicExecution.cs
- ICSharpCode.Decompiler/IL/ControlFlow/YieldReturnDecompiler.cs
- ICSharpCode.Decompiler/IL/Instructions/ILFunction.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformDisplayClassUsage.cs
N/A
ILSpy did not support yield return state machines generated by both the legacy Visual Basic compiler as well as the Roslyn Visual Basic compiler.
The following changes were made:
* Adjust detection of methods such as `MoveNext` or `Dispose` to support the interface implementations generated by the VB.NET compiler.
* Detect VB.NET `doFinallyBodies` variable used by the Legacy Visual Basic compiler.
* Add necessary code to cleanup finally blocks by removing dead conditions.
* Extend state machine detection logic for VB.NET generated code. I'm still not entirely happy with my way of detecting whether a state machine was compiled by Legacy or Roslyn Visual Basic compilers, but it works.
* Execute additional cleanup steps before analyzing `MoveNext` to …
> Add support for Visual Basic Yield Return state machine decompilation

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunDisassembler.cs
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
- NuGet.config
This late PR added the support for disassembling ReadyToRun binaries compiled using composite mode introduced officially in .NET 6.
By virtue of using the latest version, this version also supports disassembling binaries compiled using the experimental hot-cold-splitting mode introduced [here](https://github.com/dotnet/runtime/pull/74963).
Thanks @eduardo-vp for introducing the `OwnerCompositeExecutable` to make this work possible.
FYI @amanasifkhalid, @EugenioPena, this will fix https://github.com/dotnet/runtimelab/issues/1910.
> Support disassembling ReadyToRun binaries compiled using composite mode

- ILSpy/TextView/BracketHighlightRenderer.cs
- ILSpy/TextView/DecompilerTextView.cs
- ILSpy/TextView/DecompilerTextView.xaml
- ILSpy/Themes/Base.Dark.xaml
- ILSpy/Themes/Base.Light.xaml
- ILSpy/Themes/ResourceKeys.cs
- ILSpy/Themes/Theme.Dark.xaml
- ILSpy/Themes/Theme.Light.xaml
- ILSpy/Themes/Theme.RSharpDark.xaml
- ILSpy/Themes/Theme.RSharpLight.xaml
- ILSpy/Themes/Theme.VSCodeDarkPlus.xaml
- ILSpy/Themes/Theme.VSCodeLightPlus.xaml
I missed a few items which themes should have customized in #2906:
- The current line highlight
- The line numbers
- The matching brackets
The changes are pretty straightforward.
I also aligned the borders of highlighted brackets to whole pixels, as they were blurry otherwise.
Render examples:
> Add more theme colors

- ICSharpCode.Decompiler.Tests/TestCases/Correctness/DecimalFields.cs
- ICSharpCode.Decompiler/IL/Transforms/ExpressionTransforms.cs
Fixes #2949 
ILSpy did not use the proper `decimal` constructor when transforming the `LdcI4` instruction into a `LdcDecimal` instruction. Furthermore, the constructors with parameter type `long` and `ulong` were not supported at all as the pattern did not account for `LdcI8`.
Code to reproduce the missing constructor issue:
```csharp
public static decimal LongToDecimal() {
return (decimal)long.MaxValue;
}
public static decimal ULongToDecimal() {
return (decimal)ulong.MaxValue;
}
```
* Ensure the correct decimal constructor is used when creating `LdcDecimal` instructions.
* Add support for the two aforementioned previously unsupported constructors.
> Consider constructor type when lifting decimal constants

- ILSpy/ExtensionMethods.cs
- ILSpy/NativeMethods.cs
- ILSpy/Themes/WindowStyleManagerBehavior.cs
Fixes #2950
Provide an alternate approach to #2947, with less friction to existing code.
> Show a dark title bar when a dark theme in ILSpy is selected

- ILSpy/Properties/Resources.zh-Hans.resx
Chinese translation is outdated
* Add Chinese translation for "Theme" #2906 
* Translate new decompiler options
* Fix trailing space and punctuation to match the original format.
> Update Chinese translation

- .gitignore
- ICSharpCode.Decompiler.PowerShell/ICSharpCode.Decompiler.PowerShell.csproj
- ICSharpCode.Decompiler.PowerShell/manifest.psd1
Previously, `ICSharpCode.Decompiler.PowerShell` did not contain a module manifest (as stated in the README for the project).
Added a module manifest, plus the logic to copy it to the build target folder.
Please note that even with the new manifest, the module would still not be auto-discovered by PowerShell. For that to work, the compiled module (and all its dependencies) need to live in a folder on your `$env:PSModulePath` with the exact same name as the module itself; if the module is published to, and subsequently installed from, the PowerShell gallery, this requirement is automatically taken care of by PowerShellGet. 
Also, I wasn't quite sure which version no. to use in the manifest. The decompiler itself appears to be version 8.0.0.0, so that's what I …
> PowerShell module manifest

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ReduceNesting.cs
- ICSharpCode.Decompiler/IL/ControlFlow/ControlFlowSimplification.cs
Fixes https://github.com/icsharpcode/ILSpy/issues/2924
ILSpy was a bit too aggressive when it came to duplicating return blocks which resulted in unoptimal and confusing code with tons of unnecessary return statements which differed from the original source code used to produce the binary. For examples see https://github.com/icsharpcode/ILSpy/issues/2924#issue-1624058543 and https://github.com/icsharpcode/ILSpy/issues/2924#issuecomment-1502212321.
* Make the return block duplication step in `ControlFlowSimplification` less aggressive by effectively making it only perform the duplication if the incoming edge count was 1. This effectively turned it into a simple movement of a block from one container to another.
> Make return duplication in `ControlFlowSimplification` less aggressive

- ICSharpCode.Decompiler/IL/Transforms/ReduceNestingTransform.cs
N/A
When decompiling `EventPipeMetadataGenerator.GenerateMetadata(int eventId, string eventName, long keywords, uint level, uint version, EventOpcode opcode, EventParameterInfo[] parameters)` from `System.Private.CoreLib` from .NET 7.0.4 the decompiler does not completely clean up try finally regions left over from the pinned region decompilation step.
Before change:
```c#
internal unsafe byte[] GenerateMetadata(int eventId, string eventName, long keywords, uint level, uint version, EventOpcode opcode, EventParameterInfo[] parameters)
{
byte[] array = null;
bool flag = false;
try
{
uint num = (uint)(24 + (eventName.Length + 1) * 2);
uint num2 = 0u;
uint num3 = num;
if (parameters.Length == 1 && parameters[0].ParameterType == typeof(EmptyStruct))
{
parameters …
```
> Extend `EliminateRedundantTryFinally` in `ReduceNestingTransform`

- ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs
Somehow on my machine I end up with assemblies in an unexpected location in the GAC. It's most likely due to some legacy deployment script I cannot track down in the product I work on, but ILSpy should gracefully handle the case instead of crashing with an `ArgumentOutOfRangeException`:
The fix is to simply skip any detected assembly that is at the root of the GAC being enumerated.
> Fix ArgumentOutOfRangeException on unexpected file in GAC

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CompoundAssignmentTest.cs
- ICSharpCode.Decompiler/IL/ILTypeExtensions.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformAssignment.cs
Fixes https://github.com/icsharpcode/ILSpy/issues/2620
A detailed description of the issue is available here https://github.com/icsharpcode/ILSpy/issues/2620#issuecomment-1424068247.
TLDR: Compiler used `stind` for signed integer type to store the value pushed by a `conv` to an unsigned integer type which resulted in ILSpy failing to successfully introduce compound assignments.
* Implementation should be in line with what was discussed in the aforementioned issue.
@dgrunwald Please let me know if these changes are ok and do not violate the semantics of `StObj` or other ILSpy ILAst OpCodes!
> Fix decompilation of small integer pointer compound assignements

- ILSpy/Controls/ResourceObjectTable.xaml
- ILSpy/Controls/ResourceObjectTable.xaml.cs
- ILSpy/Controls/ResourceStringTable.xaml
- ILSpy/Controls/ResourceStringTable.xaml.cs
Implements #2967 
Unable to search for resource keys or values inside decompiled .resource files.
Allow filtering of the string and object tables:
String tables: filters key and value
Object tables: filters key and value string, not type
Filtering is by simple case-insensitive substring. There are no tests covering the user control as far as I can tell, let me know if I missed them. Object table for testing purposes can be found e.g. in System.Windows.Forms.
There is no watermark in the search box, it feels obvious, but happy to add one if needed.
> Search box for resource tables

- ICSharpCode.ILSpyX/ICSharpCode.ILSpyX.csproj
These packages are not needed in modern .NET; the framework provides their functionality inbox.
> Remove unnecessary package references.

- README.md
When building on macos, I got an error when using the steps from the readme.
* Update readme file to version 7 .NET SDK.
> Update readme .NET SDK -> 7.0 Unix/Mac section

- ICSharpCode.Decompiler/CSharp/RecordDecompiler.cs
As described in #3020, the decompiler fails with a NullReferenceException when attempting to decompile a record type whose base type cannot be determined (e.g. because the base type is defined in another assembly that is not loaded).
This commit updates `RecordDecompiler` to null check the `baseClass` field before making use of it.  With this fix, the null ref is avoided, but the generated code for the record will contain unnecessary `[CompilerGenerated]` members:
```
internal record RemovedSettingRegistration : SettingRegistration
{
public RemovedSettingRegistration(SettingRegistration original)
: base(original)
{
}
[CompilerGenerated]
public override string ToString() { ... }
[CompilerGenerated]
protected override bool PrintMembers(StringBuilder builder) { ... }
[CompilerGenerated] …
```
> Fix decompilation of record with missing base type

- ICSharpCode.Decompiler.Tests/ILPrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/MonoFixed.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/MonoFixed.il
- ICSharpCode.Decompiler/IL/ControlFlow/DetectPinnedRegions.cs
N/A
Decompilation of the following code compiled with MCS 2.6.4 was not properly supported and resulted in ugly and invalid code:
```csharp
fixed (char* ptr = text, userName = Environment.UserName, ptr2 = text)
{
*ptr = 'c';
*userName = 'd';
*ptr2 = 'e';
}
```
would result in:
```csharp
fixed (string text2 = text)
{
fixed (char* ptr = &System.Runtime.CompilerServices.Unsafe.AsRef<char>((char*)((long)(IntPtr)text2 + (long)RuntimeHelpers.OffsetToStringData)))
{
fixed (string text3 = Environment.UserName)
{
fixed (char* ptr2 = &System.Runtime.CompilerServices.Unsafe.AsRef<char>((char*)((long)(IntPtr)text3 + (long)RuntimeHelpers.OffsetToStringData)))
{
fixed (string text4 = text)
{
fixed (char* ptr3 = &System.Runtime.CompilerServices.Unsafe.AsRef<char>((char*)((lo …
```
> Add support for MCS 2.6.4 pinned region with string variable

- ILSpy/Controls/ResourceObjectTable.xaml
- ILSpy/Controls/ResourceObjectTable.xaml.cs
- ILSpy/Controls/ResourceStringTable.xaml
- ILSpy/Controls/ResourceStringTable.xaml.cs
Fixes #3023 
The resource tables show document context menu that does not allow copying items.
This PR adds a context menu with a few copy options.
It also fixes the issue that the normal copy uses simple ToString() which
* for object table is not overloaded and just copies the internal ILSpy type name 
* for string table it used [Key, Value] syntax
Now it separates the columns by tabs so that they can be pasted into Excel etc.
Before:
After:
> Copy key/value/names ContextMenu for resource tables

- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
Fixes #3025
- #3025
Normally, `AddTypeAnnotation` is called right after `ConvertTypeHelper` in the `ConvertType` method:
https://github.com/icsharpcode/ILSpy/blob/bf0d74d0c713a0ae231a7f650cc19d06a56c784c/ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs#L244-L245
But in the case of nested types, `ConvertTypeHelper` calls itself recursively for declaring types, and therefore `AddTypeAnnotation` was never called for these nodes.
This is a very simple change.
I couldn't find any existing unit tests which check for type annotations (`ResolveResult`), so I wasn't sure where to put this. If you'd like me to add a unit test, please tell me …
> Fix #3025: Annotate nested types

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PdbGenerationTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/Members.xml
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/SequencePointBuilder.cs
- ICSharpCode.Decompiler/CSharp/Transforms/NormalizeBlockStatements.cs
- ICSharpCode.Decompiler/DebugInfo/DebugInfoGenerator.cs
Need to visit properties and indexers in SequencePointBuilder to account for ExpressionBody.
Adds a failing test for all kinds of members. Currently failing with an unrelated duplicate sequence points for a local function body.
> Fix #3031: emit sequence points for expression-bodied properties and indexers

- ICSharpCode.ILSpyCmd/DotNetToolUpdateChecker.cs
- ICSharpCode.ILSpyCmd/ICSharpCode.ILSpyCmd.csproj
- ICSharpCode.ILSpyCmd/IlspyCmdProgram.cs
* Update McMaster.Extensions.CommandLineUtils to 4.0.1 (actually switch to McMaster.Extensions.Hosting.CommandLine for generic host support)
* Fix [DirectoryExists] for ReferencePaths due to subtle change in 3.1.0 -> 4.0.1 upgrade
* Add DotNetToolUpdateChecker.CheckForPackageUpdateAsync inspired by efcpt dotnet tool
> Update Check for ilspycmd dotnet tool

- Directory.Build.props
https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md
`<ProduceReferenceAssembly>true<ProduceReferenceAssembly>` is necessary in our case because of ics.d being netstandard2.0, otherwise this error shows up for FUTD:
```
4>FastUpToDate: Comparing timestamps of inputs and outputs: (ICSharpCode.ILSpyX)
4>FastUpToDate:     Adding UpToDateCheckBuilt outputs: (ICSharpCode.ILSpyX)
4>FastUpToDate:         D:\GitWorkspace\ILSpy\ICSharpCode.ILSpyX\bin\Debug\net6.0\ICSharpCode.ILSpyX.dll (ICSharpCode.ILSpyX)
4>FastUpToDate: Output 'D:\GitWorkspace\ILSpy\ICSharpCode.ILSpyX\bin\Debug\net6.0\ICSharpCode.ILSpyX.dll' does not exist, not up-to-date. (ICSharpCode.ILSpyX)
4>FastUpToDate: This project has enabled build acceleration, but not all referenced projects produce a reference …
```
> Accelerate local builds in Visual Studio

- ICSharpCode.Decompiler.Tests/TestCases/Correctness/ValueTypeCall.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ICSharpCode.Decompiler/IL/Transforms/ILInlining.cs
- ICSharpCode.Decompiler/IL/Transforms/SwitchOnStringTransform.cs
- packages.props
Test failures:
Records(UseRoslynLatest): ICSharpCode.Decompiler.Tests.PrettyTestRunner
Records(Optimize, UseRoslynLatest): ICSharpCode.Decompiler.Tests.PrettyTestRunner
Switch(TargetNet40, UseRoslynLatest): ICSharpCode.Decompiler.Tests.PrettyTestRunner
Switch(Optimize, TargetNet40, UseRoslynLatest): ICSharpCode.Decompiler.Tests.PrettyTestRunner
Switch(UseRoslynLatest): ICSharpCode.Decompiler.Tests.PrettyTestRunner
Switch(Optimize, UseRoslynLatest): ICSharpCode.Decompiler.Tests.PrettyTestRunner
SwitchExpressions(UseRoslynLatest): ICSharpCode.Decompiler.Tests.PrettyTestRunner
SwitchExpressions(Optimize, UseRoslynLatest): ICSharpCode.Decompiler.Tests.PrettyTestRunner
> Roslyn 4.6

- ILSpy/TextView/DecompilerTextView.cs
I was bored so I wrote this 😅
Fixes #3039
- #3039 
The text copied to the clipboard only had the basic syntax highlighting as defined in the xshd file. Additional highlighting provided by `CSharpHighlightingTokenWriter` wasn't present.
- I took the HTML copy code from AvalonEdit's `Selection.CreateHtmlFragment` as a baseline
- The new code creates a `HighlightedLine` from the active `RichTextModel`
- It then merges it into the one provided by the `IHighlighter`
The code is straightforward enough. I only wondered if this situation (having multiple `DocumentColorizingTransformer` instances) is common enough to warrant being handled by AvalonEdit …
> Copy to clipboard with full color

- .github/workflows/build-ilspy.yml
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/PatternMatching.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/CSharp/Syntax/DepthFirstAstVisitor.cs
- ICSharpCode.Decompiler/CSharp/Syntax/Expressions/RecursivePatternExpression.cs
- ICSharpCode.Decompiler/CSharp/Syntax/Expressions/UnaryOperatorExpression.cs
- ICSharpCode.Decompiler/CSharp/Syntax/IAstVisitor.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/IL/Instructions/Comp.cs
- ICSharpCode.Decompiler/IL/Instructions/MatchInstruction.cs
- ICSharpCode.Decompiler/IL/Transforms/AssignVariableNames.cs
- ICSharpCode.Decompiler/IL/Transforms/EarlyExpressionTransforms.cs
- ICSharpCode.Decompiler/IL/Transforms/ExpressionTransforms.cs
- ICSharpCode.Decompiler/IL/Transforms/PatternMatchingTransform.cs
- ICSharpCode.Decompiler/Util/Index.cs
- ILSpy.Installer/ILSpy.Installer.csproj
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
Currently not supported are:
- top-level patterns without type-checking (eg. is null, is not null, is {}, ...)
- positional pattern tuple/deconstruct
- discards in positional patterns
- not patterns (C# 9)
- relational patterns (C# 9)
- and/or pattern (C# 9)
> Support for C# 8 pattern matching

- ILSpy.ReadyToRun/Properties/Resources.Designer.cs
- ILSpy.ReadyToRun/Properties/Resources.resx
- ILSpy.ReadyToRun/Properties/Resources.zh-Hans.resx
- ILSpy.ReadyToRun/ReadyToRunDisassembler.cs
- ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml
- ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml.cs
- ILSpy.ReadyToRun/ReadyToRunOptions.cs
Fixes https://github.com/icsharpcode/ILSpy/issues/1885
Shows GC Info at the beginning and the GC transitions as well. Also it stops iterating through the whole `runtimeFunction.DebugInfo.BoundsList` for each instruction for a slight performance improvement.
> Decorate the disassembly with GCInfo

- ILSpy/TreeNodes/AssemblyTreeNode.cs
When use a single file fomart, can not found the detal size of assmessly
* Add the size info on the entry output
> Add the Entry Size Info

- ICSharpCode.Decompiler/Metadata/MetadataExtensions.cs
- ILSpy/Metadata/CorTables/ClassLayoutTableTreeNode.cs
- ILSpy/Metadata/CorTables/EventMapTableTreeNode.cs
- ILSpy/Metadata/CorTables/FieldLayoutTableTreeNode.cs
- ILSpy/Metadata/CorTables/FieldMarshalTableTreeNode.cs
- ILSpy/Metadata/CorTables/FieldRVATableTreeNode.cs
- ILSpy/Metadata/CorTables/ImplMapTableTreeNode.cs
- ILSpy/Metadata/CorTables/InterfaceImplTableTreeNode.cs
- ILSpy/Metadata/CorTables/NestedClassTableTreeNode.cs
- ILSpy/Metadata/CorTables/PropertyMapTableTreeNode.cs
- ILSpy/Metadata/DebugTables/StateMachineMethodTableTreeNode.cs
- ILSpy/Metadata/Helpers.cs
This replaces all the `unsafe` code involved in metadata parsing in the ILSpy project with the equivalent using `ReadOnlySpan<byte>`. There's a little bit left in ICSharpCode.Decompiler, mostly around resource handling.
Not sure if it's worth it, especially given possible performance regression when running on netfx, but since I already did it as an experiment, it might be useful to the project.
side note: I think all ECMA 335 metadata is little endian, but the code doesn't really seem to deal with that. I don't think .net runs on any big endian machines anymore anyway.
> Reduce "unsafe" by replacing byte* pointer usage with  ReadOnlySpan<byte>

- ILSpy/Metadata/DebugTables/CustomDebugInformationTableTreeNode.cs
N/A
The ILSpy UI incorrectly displayed `DynamicLocalVariables` and  `DefaultNamespaces`  custom debug info due to faulty return values.
* Corrected the return values
> Fix display of `DynamicLocalVariables` and `DefaultNamespaces` CDIs

- ICSharpCode.Decompiler/DebugInfo/IDebugInfoProvider.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/IL/ApplyPdbLocalTypeInfoTypeVisitor.cs
- ICSharpCode.Decompiler/IL/ILReader.cs
- ICSharpCode.ILSpyX/PdbProvider/MonoCecilDebugInfoProvider.cs
- ICSharpCode.ILSpyX/PdbProvider/PortableDebugInfoProvider.cs
fixes https://github.com/icsharpcode/ILSpy/issues/3112
ILSpy did not utilize helpful type information from PDB files when determining the type of local variables.
* Implementation as mentioned in the original issue.
* Added additional code to extract the necessary information from the PDB file and added a new `TypeVisitor` to apply this information to the type system.
> Read and use tuple element names and dynamic type information from PDBs

- ILSpy/TextView/DecompilerTextEditor.cs
- ILSpy/TextView/DecompilerTextView.xaml
- ILSpy/TextView/ThemeAwareHighlightingColorizer.cs
- ILSpy/Themes/ThemeManager.cs
Fixes #3137
Built-in highlightings of AvalonEdit are meant to be used on a white background, and look wrong on a dark one.
This PR changes the colors provided by a highlighting, unless that highlighting comes from ILSpy itself.
The color is tweaked in the [HSL color space](https://en.wikipedia.org/wiki/HSL_and_HSV), inverting the luminosity and desaturating the color a bit (as [recommended by Material Design](https://m2.material.io/design/color/dark-theme.html#ui-application)). A few coefficients are applied, I chose them after trying various solutions, as I couldn't find a known algorithm for switching a color for use in dark mode anywhere.
I …
> Adjust colors of AvalonEdit built-in highlightings for dark themes

- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs
- ICSharpCode.Decompiler/Metadata/ExportedTypeMetadata.cs
- ICSharpCode.Decompiler/Metadata/MemberReferenceMetadata.cs
- ICSharpCode.Decompiler/Metadata/ModuleReferenceMetadata.cs
- ICSharpCode.Decompiler/Metadata/PEFile.cs
- ICSharpCode.Decompiler/Metadata/TypeReferenceMetadata.cs
- ICSharpCode.Decompiler/TypeSystem/FullTypeName.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/UnknownType.cs
- ILSpy/Images/ExportOverlay.svg
- ILSpy/Images/ExportOverlay.xaml
- ILSpy/Images/Images.cs
- ILSpy/Images/README.md
- ILSpy/Images/ReferenceOverlay.svg
- ILSpy/Images/ReferenceOverlay.xaml
- ILSpy/TreeNodes/AssemblyReferenceReferencedTypesTreeNode.cs
- ILSpy/TreeNodes/AssemblyReferenceTreeNode.cs
- ILSpy/TreeNodes/ExportedTypeTreeNode.cs
- ILSpy/TreeNodes/MemberReferenceTreeNode.cs
- ILSpy/TreeNodes/ModuleReferenceTreeNode.cs
- ILSpy/TreeNodes/ReferenceFolderTreeNode.cs
- ILSpy/TreeNodes/TypeReferenceTreeNode.cs
Seeing the types/members referenced in an assembly reference is cumbersome.
Add a "Referenced Types" child node to each reference which contains the referenced types, including exported/forwarded types.
Future enhancements:
* C#-ify the names
* other children eg. ManifestResource
partially fixes https://github.com/icsharpcode/ILSpy/issues/2690. It looked like trying to add "analysis" for anything that's not `IEntity` was going to be a bad time.
> add "Referenced Types" under References

- Directory.Packages.props
- ILSpy/ILSpy.csproj
- ILSpy/TreeNodes/NaturalStringComparer.cs
- doc/third-party-notices.txt
Using NaturalSort.Extensions 4.3 that was updated for Unicode as per https://github.com/tompazourek/NaturalSort.Extension/issues/74
Benchmark https://github.com/christophwille/poc-oh/blob/main/src/NaturalSortBenchmark/README.md
> Natural Sort without interop

- Directory.Packages.props
- ILSpy.AddIn.Shared/Commands/OpenCodeItemCommand.cs
- ILSpy.AddIn.Shared/ILSpyAddInPackage.cs
- ILSpy.AddIn.Shared/ILSpyInstance.cs
- ILSpy.AddIn.VS2022/ILSpy.AddIn.VS2022.csproj
- ILSpy.AddIn/ILSpy.AddIn.csproj
- ILSpy.Tests/CommandLineArgumentsTests.cs
- ILSpy.Tests/ILSpy.Tests.csproj
- ILSpy/App.xaml.cs
- ILSpy/CommandLineArguments.cs
- ILSpy/ILSpy.csproj
- ILSpy/Properties/launchSettings.json
- ILSpy/SingleInstanceHandling.cs
- doc/Command Line.txt
- publishlocaldev.ps1
See the amended "Command Line.txt".
Notes:
* `singleInstance` is removed. Reason: if the user has a configuration for allowing multiple instances of ILSpy and there are already multiple instances actually running, we cannot enforce that parameter anyways.
* `separate` has been replaced with `newinstance`. This will always open a new instance of ILSpy irrespective of what the user has configured.
* we no longer use `/` but standard `--` for options
* we now support `@file` for passing command line parameters
* VS Addin uses the new `@file` approach
> `@file` support with breaking changes to command line options

- .github/workflows/build-ilspy.yml
- BuildTools/pre-commit
- ICSharpCode.ILSpyX/Analyzers/AnalyzerContext.cs
See also PR #2747 
```
You can invoke the tool using the following command: dotnet-format
Tool 'dotnet-format' (version '8.0.453106') was successfully installed.
8.0.453106+2651752953c0d41c8c7b8d661cf2237151af33d0
The dotnet runtime version is '8.0.7'.
Formatting code files in workspace 'Z:\GitWorkspace\ILSpy\ILSpy.sln'.
```
> Fix dotnet-format to v8 via transport feed for dotnet8

- ILSpy.Tests/Analyzers/ExportAnalyzerAttributeTests.cs
- ILSpy.Tests/ILSpy.Tests.csproj
This helps users of ILSpyX not using MEF.
Currently only ILSpyX assembly itself is searched
for annotated analyzer types.
> Allow to collect analyzers annotated with ExportAnalyzerAttribute without MEF

- Directory.Packages.props
- ILSpy/Controls/ZoomScrollViewer.cs
- ILSpy/Options/DecompilerSettingsPanel.xaml
- ILSpy/Options/DisplaySettingsPanel.xaml
- ILSpy/TextView/DecompilerTextView.xaml
supersedes #3234 by @SlimeNull; code has been cleaned up and moved to [TomsToolbox](https://github.com/tom-englert/TomsToolbox/blob/master/src/TomsToolbox.Wpf/Interactivity/SmoothScrollingBehavior.cs)
> Add smooth scrolling behavior to settings panels and DecompilerTextView

- Directory.Packages.props
- ILSpy/App.xaml
- ILSpy/Controls/ZoomScrollViewer.xaml
- ILSpy/MainWindow.xaml
- ILSpy/Metadata/Helpers.cs
- ILSpy/Options/DecompilerSettingsPanel.xaml
- ILSpy/Options/DisplaySettingsPanel.xaml
- ILSpy/Search/SearchPane.xaml
- ILSpy/TextView/DecompilerTextView.xaml
#3246
Choppy scrolling when scrolling fast after smooth scrolling introduction
Update TomsToolbox.Wpf package with fixed behavior.
> Fix #3246: Choppy scrolling when scrolling fast after smooth scrolling introduction

- ILSpy/Options/DecompilerSettingsPanel.xaml
- ILSpy/Options/DecompilerSettingsPanel.xaml.cs
- ILSpy/Options/DecompilerSettingsViewModel.cs
- ILSpy/Options/DisplaySettingsPanel.xaml
Fixes #3251 #3249
Supersedes #3250 
Decompiler Settings: Checkbox in group header does not reflect state of the group
* Move the logic from UI to ViewModel, and implement it following WPF best practices .
> Fixes #3251: Decompiler Settings: Checkbox in group header does not reflect state of the group

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/MonoFixed.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Async.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/DelegateConstruction.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/LocalFunctions.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/UnsafeCode.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/VariableNamingWithoutSymbols.cs
- ICSharpCode.Decompiler.Tests/TestCases/Ugly/AggressiveScalarReplacementOfAggregates.Expected.cs
- ICSharpCode.Decompiler/IL/Transforms/AssignVariableNames.cs
- ICSharpCode.Decompiler/IL/Transforms/ExpressionTransforms.cs
> Rewrite AssignVariableNames

- ICSharpCode.Decompiler/Metadata/DotNetCorePathFinder.cs
- ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs
#3261 
Dotnet core assemblies can not be resolved if empty folders of previously installed versions exist.
Ignore empty Directories
I changed the result of ConvertToVersion only check for empty directories where the directory is considered a fitting version. I hope that is fine.
In my case the version directories where completly empty but maybe it would make sense to look for at least one file that does have .dll or .exe extension?
I'm not sure how to test things that are environment dependend.
> Ignore empty version directories of dotnet

- ILSpy/TreeNodes/DerivedTypesTreeNode.cs
it appears Fix #3263 added an accidental `!=` instead of `==` and broke the derived types node.
no issue exists, but i can create one if desired
Derived type nodes where always empty with a build from latest version. Traced it to what appears to be a backwards null check `!= null` vs `== null`.
* Corrected the comparison, derived types tab is now populated
* need someone to verify the original issue in #3263 is still fixed by the resultant code. (I would expect it to be, but don't know how to check myself)
> Fix Derived Types Node always being empty

- ILSpy/AssemblyTree/AssemblyTreeModel.cs
- ILSpy/MainWindow.xaml
Issue: #3281
- Help -> About is broken
- Back Navigation has strange behavior
> Fix #3281: Help -> About is broken

- ILSpy/AssemblyTree/AssemblyListPane.xaml.cs
- ILSpy/AssemblyTree/AssemblyTreeModel.cs
Fix #3284: 
- Focus always moving to the assembly tree view when changing tabs
- don't decompile when just switching tabs
- AssemblyTree title is wrong
> Fix #3284: Focus, Tabs and Title issues

- Directory.Packages.props
- ICSharpCode.ILSpyX/AssemblyListManager.cs
- ILSpy/Analyzers/AnalyzerTreeView.xaml
- ILSpy/Analyzers/AnalyzerTreeViewModel.cs
- ILSpy/App.xaml.cs
- ILSpy/AssemblyTree/AssemblyListPane.xaml
- ILSpy/AssemblyTree/AssemblyListPane.xaml.cs
- ILSpy/AssemblyTree/AssemblyTreeModel.cs
- ILSpy/Commands/DecompileInNewViewCommand.cs
- ILSpy/Commands/RemoveAssembliesWithLoadErrors.cs
- ILSpy/Commands/ShowPane.cs
- ILSpy/Controls/TreeView/SharpTreeView.cs
- ILSpy/Docking/CloseAllDocumentsCommand.cs
- ILSpy/Docking/DockWorkspace.cs
- ILSpy/MainWindow.xaml.cs
- ILSpy/Util/MenuService.cs
- ILSpy/Util/SettingsService.cs
- ILSpy/ViewModels/TabPageModel.cs
- Fix #3293: Right panel shows old info in case all is deleted in the left-hand tree
- Optimize selection handling
> WPF refactoring

- ILSpy/AssemblyTree/AssemblyTreeModel.cs
... instead of the root node.
as discussed in https://github.com/icsharpcode/ILSpy/pull/3298#issuecomment-2395407799
That really looks much better
> Select first assembly from list after assembly list change

- .github/workflows/build-ilspy.yml
- BuildTools/pre-commit
https://github.com/microsoft/azure-pipelines-tasks/issues/19162 with https://github.com/dotnet/format/pull/2000
Updated to latest dotnet-format in the 8 series as the fix was merged post-RTM.
> Fix for "Unable to locate dotnet CLI. Ensure that it is on the PATH."

- Directory.Packages.props
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
- NuGet.config
Link to issue(s) this covers #3337 
This update improves the disassembly for https://github.com/dotnet/runtime/pull/98623, https://github.com/dotnet/runtime/pull/101761. These PRs added new helper calls to the runtime from ready to run native code, which could appear as opaque call to random addresses if not properly annotated.
* The diassembly for methods having calls to these new helper functions will be properly annotated with the call target
* Updated the DummyOutput to match the updated signature so that the code compile with `STRESS` defined in `ReadyToRunLanguage.cs`, and
* Tested the diassembly functionality with the .NET 9 `System.Private.CoreLib.dll` and no error found.
> Update ReadyToRun to use 9.0 package

- ILSpy/Commands/CreateDiagramContextMenuEntry.cs
- ILSpy/Docking/DockWorkspace.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/TextView/DecompilerTextView.cs
> Implement 3330: Generate diagram from UI without advanced options

- ILSpy/Controls/CustomDialog.cs
> Fix high Dpi, close #3347

- ILSpy/Controls/CustomDialog.cs
If there's `&` in text(eg. ByRef parameter in stack trace), TextRenderer will treat it as Mnemonic by default, this will cause no enough space and the text to wrap automatically.
> Fix Mnemonic

- .github/workflows/build-ilspy.yml
- Directory.Packages.props
- ICSharpCode.BamlDecompiler/ICSharpCode.BamlDecompiler.csproj
- ICSharpCode.BamlDecompiler/packages.lock.json
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/packages.lock.json
- ICSharpCode.ILSpyX/ICSharpCode.ILSpyX.csproj
- ICSharpCode.ILSpyX/packages.lock.json
- ILSpy/TreeNodes/ILSpyTreeNode.cs
https://github.com/microsoft/sbom-tool/tree/main/src/Microsoft.Sbom.Targets to embed SBOM
* GeneratePackageOnBuild removed, build action now has a new step for dotnet pack
* Decompiler, BamlDecompiler and ILSpyX include SBOM
> Use Microsoft.Sbom.Targets in ICSharpCode.Decompiler NuGet

- .github/workflows/build-frontends.yml
- .github/workflows/build-ilspy.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/generate-bom.yml
- .github/workflows/scorecard.yml
https://github.com/woodruffw/zizmor found the following problem across the board (offline mode):
```
17 |       - uses: actions/checkout@v4
|  _______-
18 | |       with:
19 | |         submodules: true
| |________________________- does not set persist-credentials: false
```
Also fixed are old versions in Scorecard.yml
> Update Scorecard actions versions and apply Zizmor offline findings

- Directory.Packages.props
https://github.com/fluentassertions/fluentassertions/releases/tag/8.0.0
We will need to stay on 7 series or switch to a different library or approach like we did with mocking libraries.
> Switch back to FluentAssertions 7.0

- ILSpy/TextView/DecompilerTextView.cs
Fixes [Lazy loaded highlight definition failing when clear and add assemblies](https://github.com/icsharpcode/ILSpy/issues/3343).
Reading from the Manifest Resource Stream inside of the RegisterHighlighting delegate seems to result in malformed reads (possibly due to threading issues).
Workaround is to read the stream before registering the delegate.
> Load resource stream outside of delegate

- ILSpy/ILSpy.csproj
Allow `ILSpy.exe` to launch when .NET 8 (the version it currently targets) is not installed, but some later major version (e.g. .NET 9) is available instead.
ref. https://learn.microsoft.com/en-us/dotnet/core/versions/selection#control-roll-forward-behavior
https://github.com/icsharpcode/ILSpy/issues/3390
> Enable `<RollForward>major</RollForward>` for `ILSpy.exe`

- Directory.Packages.props
- ILSpy/AssemblyTree/AssemblyTreeModel.cs
#3402: System.NullReferenceException on right click on .NET 9
* Fixed in TomsToolbox
https://github.com/tom-englert/TomsToolbox/commit/31b9dd57974512ba3d27a17bc25a25f802d4cb34
> Fix #3402: System.NullReferenceException on right click on .NET 9

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/InitializerTests.cs
- ICSharpCode.Decompiler/IL/Transforms/ExpressionTransforms.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformArrayInitializers.cs
Resolves #3379 
* I tried to make it very similar to the code for `Span<T>(void*, int)`.
* Testing. I'm happy to write additional tests and modify my existing test.
> Replace `RuntimeHelpers.CreateSpan<T>(LdMemberToken)` with `new T[] { }`

- ICSharpCode.Decompiler/Util/ResXResourceWriter.cs
Version [9.0.0.7889](https://www.nuget.org/packages/ICSharpCode.Decompiler/9.0.0.7889) throws a NullReferenceException when trying to write a resx file without calling AddResource() due to the uninitialized writer.
Initialize the writer during Generate, in case it was not initialized yet.
> Fix exception when writing resx files without adding any resources

- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/GuessAccessors.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CompoundAssignmentTest.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/DelegateConstruction.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExceptionHandling.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/RefLocalsAndReturns.cs
- ICSharpCode.Decompiler.Tests/TestCases/VBPretty/Async.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
- ICSharpCode.Decompiler/CSharp/Transforms/CombineQueryExpressions.cs
- ICSharpCode.Decompiler/CSharp/Transforms/IntroduceQueryExpressions.cs
- ICSharpCode.Decompiler/IL/ControlFlow/AsyncAwaitDecompiler.cs
- ICSharpCode.Decompiler/IL/ControlFlow/YieldReturnDecompiler.cs
- ICSharpCode.Decompiler/IL/ILReader.cs
- ICSharpCode.Decompiler/IL/Instructions/ILFunction.cs
- ICSharpCode.Decompiler/IL/Transforms/AssignVariableNames.cs
- ICSharpCode.Decompiler/Util/CollectionExtensions.cs
Link to issue(s) this covers: #1572, #1956, #2439, #2694 
Needs more thorough testing on larger code bases, but it will be hard to verify the results.
@tamlin-mike @yyjdelete @greenozon
@dgrunwald I suspect that the "allow shadowing of names in local functions / lambdas" language feature could be implemented in ILSpy by making sure that no variables in the ILFunction.CapturedVariables list have the same name as any local variable or parameter? The changes in this PR only introduce the concept of a scope per ILFunction, so parameters of "independent" lambdas such as `list.Where(x => x > 5).Select(x => x * 2)` are allowed even without the setting, but nested lambdas that "shadow" a lambda parameter, but don't use any variable from a parent scope are not allowed right now.
> Add scopes to AssignVariableName

- ICSharpCode.Decompiler.PowerShell/GetTargetFramework.cs
- ICSharpCode.Decompiler.PowerShell/manifest.psd1
Sometimes it is helpful to validate that all the assemblies in a directory are targeting the expected framework(s).
Adding a simple PS cmdlet to output the target framework for an assembly using PowerShell.
> PSCmdLet to output target framework for an assembly

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/ILPrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Issue3442.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Issue3442.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Issue3442.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
> Don't include generic constraints in generated explicit overrides

- .github/workflows/build-ilspy.yml
- ICSharpCode.Decompiler.Tests/CorrectnessTestRunner.cs
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/TestCases/Correctness/NonGenericConstrainedCallVirt.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Generics.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/CallBuilder.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/IL/ILReader.cs
- ICSharpCode.Decompiler/IL/Instructions.cs
- ICSharpCode.Decompiler/IL/Instructions.tt
- ICSharpCode.Decompiler/IL/Instructions/CallInstruction.cs
- ICSharpCode.Decompiler/IL/Instructions/PatternMatching.cs
- ICSharpCode.Decompiler/IL/Transforms/ExpressionTransforms.cs
- ICSharpCode.Decompiler/IL/Transforms/IILTransform.cs
- ICSharpCode.Decompiler/IL/Transforms/ILInlining.cs
- ICSharpCode.Decompiler/IL/Transforms/NamedArgumentTransform.cs
- ICSharpCode.Decompiler/IL/Transforms/NullPropagationTransform.cs
- ICSharpCode.Decompiler/IL/Transforms/RemoveInfeasiblePathTransform.cs
- ICSharpCode.Decompiler/IL/Transforms/RemoveUnconstrainedGenericReferenceTypeCheck.cs
- ICSharpCode.Decompiler/IL/Transforms/SplitVariables.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformCollectionAndObjectInitializers.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformExpressionTrees.cs
- ICSharpCode.Decompiler/IL/Transforms/UsingTransform.cs
- ILSpy/Languages/ILAstLanguage.cs
Reason: Recent changes in the runtime as well as Roslyn fixing an eval order bug of constrained calls.
#3438 
#3419
I will clean up the PR before merge.
> Fix changes due to eval order fix

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Issue1918.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CS73_StackAllocInitializers.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/PointerArithmetic.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/UnsafeCode.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
Resolves #3411 
This makes pointer arithmetic prettier with the help of available type hints.
* I tried to be as surgical as possible.
* There was a slight behavior change involving `sbyte*` vs `byte*`. I want to know if that's okay or not. Previously, `byte*` got picked because it's the default when things go wrong. However, now the type hint (which is often signed) prevents some of those situations.
* I think the type hints could be better if they had sign information in more cases, but I was hesitant to change the code that sets the type hint.
> Use type hint in pointer arithmetic

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/ProjectDecompiler/TargetFrameworkTests.cs
- ICSharpCode.Decompiler.Tests/ProjectDecompiler/WholeProjectDecompilerTests.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs
- ILSpy.BamlDecompiler/BamlResourceNodeFactory.cs
Resolves #3448 
31bbcf41bcb0dcd0b3e019bc56fa158d8ac37f70 introduced a regression, preventing the `UseNestedDirectoriesForNamespaces` from functioning as intended.
* As part of my testing, I added two API methods to `WholeProjectDecompiler`.
* ~~`BamlResourceNodeFactory::WriteResourceToFile` also uses this method, which I think is incorrect, but I'm not sure what to change it to.~~
> Fix nested namespace directories

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/GloballyQualifiedTypeInStringInterpolation.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/InsertParenthesesVisitor.cs
Resolves #3447 
* As recommended, I implemented the fix in the `InsertParenthesesVisitor` class.
* I used recursion to check if any child has `global::`. Is there a better (more performant) way to check?
> Parenthesize interpolations containing `global::`

- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs
`TryOpenStream` can return null, and we previously didn't check for that.
* It's similar to the null checks for miscellaneous files.
> Fix null reference exception when writing resource files

- ICSharpCode.Decompiler/Disassembler/ReflectionDisassembler.cs
According to the grammar of [ilasm](https://github.com/dotnet/runtime/blob/81899bbcb38ef43ae73b0eaf5dcf38234f8d875b/src/coreclr/ilasm/prebuilt/asmparse.grammar#L531), this should be `flags` instead of `flag`.
> Correct flag to flags

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/ILPrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Issue3466.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Issue3466.il
- ICSharpCode.Decompiler/CSharp/Resolver/CSharpResolver.cs
> Fix stack overflow exception in CSharpResolver

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/OptionalArguments.cs
- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ICSharpCode.Decompiler/TypeSystem/IParameter.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataParameter.cs
- ICSharpCode.Decompiler/TypeSystem/TypeSystemExtensions.cs
Resolves #3469 
* I implemented this in an extensions class, which is a little bit removed from the code that uses it.
* Do you think my extension method needs more documentation?
* Should there be any additional tests involving decimal constants?
> Handle explicit optional parameter after default parameter

- ICSharpCode.Decompiler/Metadata/MetadataFile.cs
- ICSharpCode.Decompiler/Metadata/PEFile.cs
`System.Reflection.Metadata` allows specifying a `System.Reflection.Metadata.MetadataStringDecoder` to your `MetadataReader` to cache any strings it allocates, thereby reducing allocations.
I have an existing `MetadataReader` that is using my custom `MetadataStringDecoder`, however `ICSharpCode.Decompiler.Metadata.MetadataFile` does not allow me to pass in my existing `MetadataReader`, it instead requires that I pass in a `System.Reflection.Metadata.MetadataReaderProvider`.
If `MetadataReaderProvider.GetMetadataReader` is called multiple times with the same inputs, the same `MetadataReader` will be returned each time. I thought that maybe I could create a `MetadataReaderProvider` to get the `MetadataReader` that I and `ICSharpCode.Decompiler` both need to use, however `GetMetadataReader` …
> Allow creating a MetadataFile with a MetadataReader / MetadataStringDecoder

- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/TargetFramework.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/TargetServices.cs
Custom project writers cannot currently make use of TargetFramework and TargetServices because they're not public.
My specific use case is: I am using ILSpy in my Godot decompiler to add support for decompiling games with C# scripts. One of the quirks about building a C# project for Godot is that the SDK in the `csproj` is labelled as `Godot.NET.Sdk`, and there are custom assemblies that are automatically included without references, so I had to make a custom project writer for this and pass it into `WholeProjectDecompiler`.
I currently have to copy a bunch of files, including these, because they're not public; since we explicitly provide the ability to pass in a custom project writer to the decompiler, I think that they should be made public so that others can make use of them.
* What it …
> Make TargetFramework and TargetServices public

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/ILPrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Issue3504.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/Issue3504.il
- ICSharpCode.Decompiler/TypeSystem/MetadataModule.cs
ILSpy could match an instance method call with a static method reference. This can happen when resolving a method whose *current* definition is `static` but the IL actually calls an instance method. I.e. the method was originally an instance method but was changed to `static`.
This results in the decompiled code to silently drop the instance argument on the evaluation stack. While this produces valid/compilible C# code, it does not accurately decompile the given code.
Example:
the reference code was changed from
```cs
class A {
static A instance;
void Ref() {}
}
```
to
```cs
class A {
static A instance;
static void Ref() {}
}
```
the original code is
```cs
A.instance.Ref();
```
but gets wrongly decompiled to
```cs
A.Ref(); // should still be A.instance.Ref();
```
* The given code searches …
> Fix incorrect method match for static methods with instance signature

- Directory.Packages.props
- ILSpy/ILSpy.csproj
- ILSpy/TreeNodes/NaturalStringComparer.cs
- doc/third-party-notices.txt
In .NET 10 since preview1, see https://github.com/dotnet/core/blob/main/release-notes/10.0/preview/preview1/libraries.md#numeric-ordering-for-string-comparison
@tompazourek thanks for https://github.com/tompazourek/NaturalSort.Extension/ - it was great to have that available pre-net10!
Tested in https://github.com/christophwille/poc-oh/commit/f8e4ebf26c480f22212d78a4868921abb374d871
> Remove NaturalSort.Extension for net10 in-built CompareOptions.NumericOrdering

- Directory.Packages.props
- ICSharpCode.BamlDecompiler/packages.lock.json
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/packages.lock.json
- ICSharpCode.ILSpyCmd/packages.lock.json
- ICSharpCode.ILSpyX/packages.lock.json
* Bump all Microsoft.* and System.* to 10.0.0-preview5
* Microsoft.CodeAnalysis.* to 4.14.0
* Update other dependencies to latest
`msbuild --restore /p:RestoreForceEvaluate=true /p:RestoreEnablePackagePruning=false ILSpy.sln` to update packages.lock.json
> .NET 10.0 Preview5 NuGet Updates

- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/TargetServices.cs
- ICSharpCode.Decompiler/Solution/SolutionCreator.cs
- ILSpy/Commands/SaveCodeContextMenuEntry.cs
- ILSpy/SolutionWriter.cs
[Link to issue(s) this covers](https://github.com/icsharpcode/ILSpy/issues/2875)
The XML namespace isn't correctly configured when using new-style solution files.
There are three changes in this PR; I bundled them here as they are near in code and I didn't think anyone would object to the cleanup. (Please let me know if you'd rather I split up the changes.)
* Cleanup use of repeated enumeration of an IEnumerable<T> in a public API
* Change project guids to be written in lower-case (this fixes compatibility with some old Microsoft tools, I believe no other common tools care either way, and the uuid RFC specifies lower-case)
* Detects whether the solution is an SDK-style by examining its xml and chooses the XML namespace appropriately (this is the fix for issue 2875)
> Fix SDK-style (modern) inter-project references

- ILSpy/Commands/ExtractPackageEntryContextMenuEntry.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/Properties/Resources.zh-Hans.resx
Close https://github.com/icsharpcode/ILSpy/issues/3498
I see this file structure:
```
runtimes/win-x64/native  // folder
WebViewer2Loader     // file
```
I don't know if following is also possible:
```
runtimes                        // folder
win-x64                     // folder
native                  // folder
WebViewer2Loader    // file
```
If it's impossible, recursion is unnecessary in GetFullPath
> Extract multiple package entries

- ICSharpCode.Decompiler.Tests/DisassemblerPrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Disassembler/Pretty/GenericConstraints.il
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Generics.cs
- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ICSharpCode.Decompiler/Disassembler/ReflectionDisassembler.cs
- ICSharpCode.Decompiler/TypeSystem/ITypeParameter.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/AbstractTypeParameter.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/DefaultTypeParameter.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/DummyTypeParameter.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataTypeParameter.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/NullabilityAnnotatedType.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/SpecializedMethod.cs
- ICSharpCode.Decompiler/TypeSystem/TypeUtils.cs
Part of https://github.com/icsharpcode/ILSpy/issues/3430. Decompiling to IL doesn't show `byreflike` constraint. Similarly, decompiling to C# doesn't show `allows ref struct` constraint.
> Support `allows ref struct` constraint

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
I wish to provide my own custom `IDecompilerTypeSystem` to `CSharpDecompiler`. The existing constructor `CSharpDecompiler(DecompilerTypeSystem typeSystem, DecompilerSettings settings)` limits to you to specifying a value of the concrete `DecompilerTypeSystem` type, however this value is assigned to the `typeSystem` field which is of type `IDecompilerTypeSystem`. I did not see any restrictions that require that the `IDecompilerTypeSystem` that is used *must* either be of type `DecompilerTypeSystem` or `SimpleCompilation` (which `DecompilerTypeSystem` derives from) so I am proposing to modify the type of `typeSystem` constructor parameter to match the type of the field that it then assigns to
> Allow specifying an IDecompilerTypeSystem rather than a DecompilerTypeSystem to CSharpDecompiler

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExpandParamsArgumentsDisabled.cs
- ICSharpCode.Decompiler/CSharp/CallBuilder.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
As discussed in #3533, this adds a new decompile setting to toggle whether to expand params arguments
> Add ExpandParamsArguments DecompilerSettings

- .editorconfig
- .gitignore
- ICSharpCode.ILSpyCmd/IlspyCmdProgram.cs
- ICSharpCode.ILSpyX/MermaidDiagrammer/GenerateHtmlDiagrammer.cs
- ICSharpCode.ILSpyX/MermaidDiagrammer/Generator.Run.cs
Minor fixes that seemed like they're small enough to bundle together for review (there should be no run-time change in behavior):
* Removed duplicate settings in .editorconfig.
* Fix invalid .editorconfig value (valid values for csharp_space_around_declaration_statements seem to be "false" and "ignore"; "do_not_ignore" currently is equivalent to false based on https://github.com/dotnet/roslyn/issues/28022).
* Change .gitignore to ignore all .vscode folders, not just a top-level one.
* Typo fix (ReportExludedTypes -> ReportExcludedTypes)
> Minor Dev Environment Fixes (.editorconfig cleanup, typo fix, .gitignore tweak)
