icsharpcode/ILSpy

- ILSpy/Options/DecompilerSettingsPanel.xaml
- ILSpy/Options/DecompilerSettingsPanel.xaml.cs
Added switch to enable/disable decompiling of expression trees in the settings panel.
> Added switch to enable/disable decompiling of expression trees in settings panel.

- ICSharpCode.Decompiler/ILAst/StateRange.cs
- ICSharpCode.Decompiler/Tests/Async.cs
> Fixed decompiling empty async methods.

- ILSpy/CommandLineArguments.cs
- ILSpy/Languages/CSharpLanguage.cs
- ILSpy/MainWindow.xaml.cs
- ILSpy/VB/VBLanguage.cs
all assemblies passed on the commandline are exported to this dir.
> Add commandline arguments for a fixed guid, and export dir

- ICSharpCode.Decompiler/Ast/AstMethodBodyBuilder.cs
- ICSharpCode.Decompiler/ILAst/ILAstOptimizer.cs
- ICSharpCode.Decompiler/ILAst/TypeAnalysis.cs
- ICSharpCode.Decompiler/Tests/UnsafeCode.cs
This doesn't fix all pointer arithmetic issues, but most of them.
Partially fixes #271
> Redundant IntPtr casts with pointer arithmetic

- ICSharpCode.Decompiler/ILAst/StateRange.cs
- ICSharpCode.Decompiler/Tests/Async.cs
Reverts icsharpcode/ILSpy#487 due to #551
> Revert "Fixed decompiling empty async methods."

- ILSpy/AboutPage.cs
This prevents WebRequest.GetSystemWebProxy() from blocking UI
> Get Proxy Server for Web Client asynchronously

- ICSharpCode.Decompiler/Ast/Transforms/IntroduceUnsafeModifier.cs
- ICSharpCode.Decompiler/ILAst/ILAstOptimizer.cs
- ICSharpCode.Decompiler/ILAst/TypeAnalysis.cs
- ICSharpCode.Decompiler/Tests/UnsafeCode.cs
This fixes more complex pointer addition/subtraction examples, like PointerArithmetic3 and 4 test cases. Test case 2 is still failing.
Fixes #565
Fixes #400
Succeeds #576
Fixes #592
Partially fixes #569
> Enhanced pointer arithmetic handling

- BuildTools/UpdateAssemblyInfo/Main.cs
- ILSpy/MainWindow.xaml.cs
- ILSpy/TreeNodes/AssemblyListTreeNode.cs
when my cmd starts, there is a banner (i.e doskey), so assume that the first line is a commit isn't good in this case.
> UpdateAssemblyInfo.exe failed when there is a banner in start of cmd

- ICSharpCode.Decompiler/Ast/AstBuilder.cs
> Fixed #619 custom attributes on enum members

- ILSpy/SearchStrategies.cs
Added
* - for not contain
* = for equal
* + for contain
for the search field.
> Changed SearchStrategies

- ICSharpCode.Decompiler/Ast/Transforms/PatternStatementTransform.cs
- ICSharpCode.Decompiler/Tests/FSharpPatterns/FSharpPatternTests.cs
- ICSharpCode.Decompiler/Tests/FSharpPatterns/FSharpUsing.fs
- ICSharpCode.Decompiler/Tests/FSharpPatterns/FSharpUsing.fs.Debug.cs
- ICSharpCode.Decompiler/Tests/FSharpPatterns/FSharpUsing.fs.Debug.il
- ICSharpCode.Decompiler/Tests/FSharpPatterns/FSharpUsing.fs.Release.cs
- ICSharpCode.Decompiler/Tests/FSharpPatterns/FSharpUsing.fs.Release.il
- ICSharpCode.Decompiler/Tests/FSharpPatterns/TestHelpers.cs
- ICSharpCode.Decompiler/Tests/FSharpPatterns/TestRunner.cs
- ICSharpCode.Decompiler/Tests/FSharpPatterns/ToolLocator.cs
- ICSharpCode.Decompiler/Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler/Tests/NotUsingBlock.cs
- ICSharpCode.Decompiler/Tests/TestRunner.cs
- ICSharpCode.Decompiler/Tests/packages.config
https://gist.github.com/0x53A/5c8dedc0be448a299386#file-c-with-my-changes
> modify the using pattern to also detect F# [#670]

- ILSpy/Controls/ResourceStringTable.xaml
Reverts icsharpcode/ILSpy#681 due to performance issues with large files.
> Revert "Allow scrolling in high resource rows"

- ILSpy/App.xaml.cs
- ILSpy/CommandLineArguments.cs
- ILSpy/ILSpy.csproj
- ILSpy/Options/MiscSettings.cs
- ILSpy/Options/MiscSettingsLoader.cs
- ILSpy/Options/MiscSettingsPanel.xaml
- ILSpy/Options/MiscSettingsPanel.xaml.cs
Resolved the issue Global config switch for separate instances #810
`https://github.com/icsharpcode/ILSpy/issues/810`
Created an option to allow user modify if he wants multiple enabled or not
> Allow Multiple Instance Option and Dialog

- ICSharpCode.Decompiler.Console/CustomAssemblyResolver.cs
- ICSharpCode.Decompiler/CSharp/WholeProjectDecompiler.cs
Ignore formatting changes:
https://github.com/icsharpcode/ILSpy/compare/master...mohe2015:fix-assembly-resolution?w=1
> Don't crash if assembly resolution fails.

- ICSharpCode.Decompiler/IL/Transforms/CopyPropagation.cs
I give it a try :) Closes #885 
TODO: add testcase
> Fix failed decompilation of catch-when if the method is async.

- ILSpy/TreeNodes/AssemblyListTreeNode.cs
I just added support for dropping nupkg as suppested by @siegfriedpammer in issue #986 .
Feedback is welcome.
> Added support for dropping nupkg files.

- ICSharpCode.Decompiler.Tests/Helpers/Tester.cs
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/Util/SequencePointTests.cs
This is just a unit-test to simplify debugging CreateSequencePoints. Not necessarily to be committed, up to you.
> Add a unit-test for CreateSequencePoints

- ILSpy/AboutPage.cs
- ILSpy/App.xaml.cs
- ILSpy/ContextMenuEntry.cs
- ILSpy/ILSpy.csproj
- ILSpy/Languages/CSharpLanguage.cs
- ILSpy/Languages/Languages.cs
- ILSpy/MainWindow.xaml.cs
- ILSpy/Options/OptionsDialog.xaml.cs
- ILSpy/TreeNodes/ResourceNodes/ResourceEntryNode.cs
- ILSpy/TreeNodes/ResourceNodes/ResourceTreeNode.cs
- TestPlugin/AboutPageAddition.cs
- TestPlugin/TestPlugin.csproj
This switches from an MEF1 CompositionContainer to a VS MEF ExportProvider for the extensibility processing.
> Issue #1046: Use VS MEF for hosting

- ICSharpCode.Decompiler/IL/ControlFlow/YieldReturnDecompiler.cs
- ICSharpCode.Decompiler/IL/Transforms/DelegateConstruction.cs
Trying to resolve (see #1269, #1152, #1057, #1025) without messing up with current implementation.
> Fix yield return for assembly compiled with Mono

- ILSpy/MainWindow.xaml.cs
- ILSpy/Options/MiscSettings.cs
- ILSpy/Options/MiscSettingsPanel.xaml
- ILSpy/Options/MiscSettingsPanel.xaml.cs
This adds the ability to not re-load previously loaded libraries, issue #1401
> Add option to not reload assemblies

- ICSharpCode.Decompiler.PdbProvider.Cecil/ICSharpCode.Decompiler.PdbProvider.Cecil.csproj
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.nuspec.template
- ILSpy.AddIn/ILSpy.AddIn.csproj
- ILSpy.BamlDecompiler.Tests/ILSpy.BamlDecompiler.Tests.csproj
- ILSpy.BamlDecompiler/ILSpy.BamlDecompiler.csproj
- ILSpy.Tests/ILSpy.Tests.csproj
- ILSpy/ILSpy.csproj
- ILSpy/Properties/app.config.template
- SharpTreeView/ICSharpCode.TreeView.csproj
- TestPlugin/TestPlugin.csproj
- appveyor.yml
> Tfm updates

- ICSharpCode.Decompiler.Console/Program.cs
Implements https://github.com/icsharpcode/ILSpy/issues/1244
> Add -d option (pdb generation)

- ILSpy.BamlDecompiler/ILSpy.BamlDecompiler.csproj
- ILSpy/ILSpy.csproj
- ILSpy/Properties/app.config.template
See issue https://github.com/icsharpcode/ILSpy/issues/1606
> Use AE 6 preview to verify API compat (as well as runtime functionality)

- ICSharpCode.Decompiler/IL/ControlFlow/AsyncAwaitDecompiler.cs
Unfortunately, I am unable to produce a simple test case. Might be necessary to create an IL pretty test.
> Fix #1632: await pattern might use negated IsCompleted check.

- ICSharpCode.Decompiler.Tests/Helpers/Tester.cs
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CustomTaskType.cs
- ICSharpCode.Decompiler/IL/ControlFlow/AsyncAwaitDecompiler.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/KnownAttributes.cs
- ICSharpCode.Decompiler/TypeSystem/TaskType.cs
* Adds support for C# 7.0 Generalized async return types
* Fixes #1651
> C# 7.0 Generalized async return types

- ILSpy.AddIn/ILSpy.AddIn.csproj
Fixes https://github.com/icsharpcode/ILSpy/issues/1418
> Addin: Change Package References

- ILSpy/ILSpy.csproj
- ILSpy/MainWindow.xaml.cs
- ILSpy/Search/NamespaceSearchStrategy.cs
- ILSpy/Search/SearchPane.cs
- ILSpy/Search/SearchResult.cs
- ILSpy/TreeNodes/AssemblyListTreeNode.cs
> Add namespace search strategy

- ILSpy/ILSpy.csproj
For issue #1731 
Applied fix suggested in https://github.com/dotnet/sdk/issues/3708#issuecomment-539254182
> Build Order Bug Fix

- ICSharpCode.Decompiler.Console/IlspyCmdProgram.cs
- ICSharpCode.Decompiler.Console/README.md
- ICSharpCode.Decompiler.PowerShell/GetDecompilerCmdlet.cs
> Fix issue 1677

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs
- ILSpy/LoadedAssembly.cs
> Fix issue #1762

- ILSpy/Commands/DecompileInNewViewCommand.cs
- ILSpy/Docking/DockWorkspace.cs
- ILSpy/MainWindow.xaml.cs
> Fixes #1812

- ILSpy/Analyzers/AnalyzerScope.cs
> Follow type forward in AnalyzerScope

- ICSharpCode.Decompiler/CSharp/Transforms/DeclareVariables.cs
- ICSharpCode.Decompiler/CSharp/Transforms/PatternStatementTransform.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ICSharpCode.Decompiler/IL/Transforms/HighLevelLoopTransform.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
Add ForStatement, DoWhileStatement and SeparateLocalVariableDeclarations settings.
This fixes #1848
@dgrunwald please review my changes to the DeclareVariables transform. Thank you very much!
/cc @Piedone
> Additional settings #1848

- ICSharpCode.Decompiler.Console/ICSharpCode.Decompiler.Console.csproj
- ICSharpCode.Decompiler.Console/IlspyCmdProgram.cs
- ICSharpCode.Decompiler.Console/ValidationAttributes.cs
- ICSharpCode.Decompiler.PdbProvider.Cecil/MonoCecilDebugInfoProvider.cs
- ICSharpCode.Decompiler.PowerShell/GetDecompilerCmdlet.cs
- ICSharpCode.Decompiler.PowerShell/ICSharpCode.Decompiler.PowerShell.csproj
- ILSpy/DebugInfo/DebugInfoUtils.cs
- ILSpy/DebugInfo/PortableDebugInfoProvider.cs
- ILSpy/ILSpy.csproj
- ILSpy/LoadedAssembly.cs
derived from work by @an-dr-eas-k in #1679
> Add PDB support to powershell and command-line frontends

- ICSharpCode.Decompiler.Console/ICSharpCode.Decompiler.Console.csproj
- ICSharpCode.Decompiler.Tests/Helpers/Tester.cs
- README.md
- azure-pipelines.yml
- global.json
Only to be merged once AppVeyor is ready
> Move to .NET Core 3.1 SDK

- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
> Fix #1889: [ILSpy.ReadyToRun] Indexing the methods

- ILSpy/Properties/AssemblyInfo.template.cs
> v6 RTM RevisionClass

- ICSharpCode.Decompiler.Tests/Helpers/Tester.cs
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/LocalFunctions.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/CallBuilder.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpAmbience.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs
- ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
- ICSharpCode.Decompiler/CSharp/Syntax/Statements/LocalFunctionDeclarationStatement.cs
- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ICSharpCode.Decompiler/CSharp/Transforms/ContextTrackingVisitor.cs
- ICSharpCode.Decompiler/IL/Transforms/AssignVariableNames.cs
- ICSharpCode.Decompiler/IL/Transforms/LocalFunctionDecompiler.cs
- ICSharpCode.Decompiler/Output/TextTokenWriter.cs
- ICSharpCode.Decompiler/TypeSystem/Implementation/LocalFunctionMethod.cs
- ILSpy/Languages/CSharpLanguage.cs
> Attributes on local functions

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
This is reacting to https://github.com/dotnet/runtime/pull/41303.
> Adapting to the changes proposed by Tomas

- ILSpy/Properties/Resources.zh-Hans.resx
update Chinese translation
finished
> Update Chinese translation

- ICSharpCode.Decompiler.Console/ICSharpCode.Decompiler.Console.csproj
- ICSharpCode.Decompiler.PdbProvider.Cecil/ICSharpCode.Decompiler.PdbProvider.Cecil.csproj
- ICSharpCode.Decompiler.PowerShell/ICSharpCode.Decompiler.PowerShell.csproj
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.nuspec.template
- ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs
- ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs
- ILSpy.AddIn/AssemblyFileFinder.cs
- ILSpy.AddIn/Commands/OpenReferenceCommand.cs
- ILSpy.AddIn/Commands/ProjectReferenceForILSpy.cs
- ILSpy.AddIn/Decompiler/Dummy.cs
- ILSpy.AddIn/ILSpy.AddIn.csproj
- ILSpy.BamlDecompiler.Tests/ILSpy.BamlDecompiler.Tests.csproj
- ILSpy.BamlDecompiler/ILSpy.BamlDecompiler.csproj
- ILSpy.Tests/ILSpy.Tests.csproj
- ILSpy/ILSpy.csproj
- ILSpy/Properties/app.config.template
- packages.props
> Update NuGet Dependencies

- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/Util/FileUtilityTests.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/IProjectInfoProvider.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/ProjectFileWriterDefault.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/ProjectFileWriterSdkStyle.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/TargetServices.cs
- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs
- ICSharpCode.Decompiler/CSharp/Transforms/EscapeInvalidIdentifiers.cs
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/Metadata/AssemblyReferences.cs
- ICSharpCode.Decompiler/Metadata/DotNetCorePathFinder.cs
- ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs
- ICSharpCode.Decompiler/Util/FileUtility.cs
- ICSharpCode.Decompiler/Util/Win32Resources.cs
- ILSpy/LoadedAssembly.cs
Restores PR #2157...
I am very sorry for destroying the other PR.
> Restore #2157 Improving csproj Export (Save Code)

- ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs
makes GetFileNameForResource in accordance with CleanUpDirectoryName
> fix GetFileNameForResource not in accordance with new directory style

- .github/workflows/build-frontends.yml
Run Debug build for Frontends.sln on push to master & PR
> Add GH Action for building Frontends.sln

- packages.props
https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/ is available in v3.8.0 final
> Microsoft.CodeAnalysis 3.8.0 RTM

- .github/workflows/codeql-analysis.yml
- DecompilerNuGetDemos.workbook
- ICSharpCode.Decompiler.Console/ICSharpCode.Decompiler.Console.csproj
- ICSharpCode.Decompiler.PowerShell/ICSharpCode.Decompiler.PowerShell.csproj
While browsing the PowerShell repository I remembered that I wanted to set up code scanning here too.
See https://github.com/github/codeql-action
Can be merged only after v7p1 NuGet is published (API change)
> CodeQL Action

- .github/workflows/codeql-analysis.yml
dotnet restore seems to not like our conditional for Debug -> csproj, Release -> nupkg
> CodeQL: Conditional NuGet restore of ICS.D fails

- ILSpy/Options/DisplaySettings.cs
- ILSpy/Options/DisplaySettingsPanel.xaml
- ILSpy/Options/DisplaySettingsPanel.xaml.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/TextView/DecompilerTextView.cs
Issue https://github.com/icsharpcode/ILSpy/issues/2208 mentions highlighting the current line.
I revived a old version of mine were I had this locally, and made a PR for it.
I added a setting to enable/disable the highlighted line - default is disabled like it is now.
If you don't want like/want this, feel free to close this PR.
> Added setting to highlight the current line

- ILSpy.ReadyToRun/ReadyToRunDisassembler.cs
- ILSpy.ReadyToRun/ReadyToRunLanguage.cs
The PR fixes a few bugs in debug info decoration. See [my investigation notes](https://cshung.github.io/posts/debug-info-debugging/) for more information about this fix.
> Fix some bugs in debug info decoration for ReadyToRun

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ExpressionTrees.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformExpressionTrees.cs
https://github.com/icsharpcode/ILSpy/issues/2288
Wrong nullable value type expression decompilation
> Fix wrong nullable lift

- ILSpy.BamlDecompiler/ILSpy.BamlDecompiler.csproj
- ILSpy/Docking/DockLayoutSettings.cs
- ILSpy/Docking/DockWorkspace.cs
- ILSpy/ILSpy.csproj
- ILSpy/MainWindow.xaml
- ILSpy/MainWindow.xaml.cs
- TestPlugin/Properties/launchSettings.json
- packages.props
* Dirkster.AvalonDock
* System.Composition
* OSVersionHelper
* DataGridExtensions
* Microsoft.Xaml.Behaviors.Wpf
> Update nuget packages

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/QualifierTests.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/TranslatedExpression.cs
> Ensure base references have the correct type

- ILSpy/Search/AbstractEntitySearchStrategy.cs
As discussed in #2335, adjust calculation of fitness for destructors.
> Adjust fitness calculation for desctructors

- ILSpy.AddIn/ILSpy.AddIn.csproj
Cherry-picking changes from #2346 as requested by @sharwell.
@sharwell  are you OK with these changes?
@tom-englert fyi
> Modernize Visual Studio AddIn csproj part 1

- ILSpy/App.xaml.cs
- ILSpy/ILSpy.csproj
- SharpTreeView/ICSharpCode.TreeView.csproj
> Fix UI and theming issues #2359

- doc/third-party-notices.txt
just update some outdated copyrights
> Update copyrights for DataGridExtensions and TomsToolbox

- ILSpy/ILSpy.csproj
- SharpTreeView/ICSharpCode.TreeView.csproj
> #2359: Adjust checkable style of MenuItem

- ILSpy/MainWindow.xaml
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/Properties/Resources.zh-Hans.resx
> Translate new words to Chinese

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/RefLocalsAndReturns.cs
- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ICSharpCode.Decompiler/CSharp/Transforms/PatternStatementTransform.cs
> Fix #2406: for readonly property with only getter, move readonly to property instead of getter

- ILSpy.Package/ILSpy.Package.wapproj
See original build break #2422
See also https://developercommunity2.visualstudio.com/t/Desktop-Bridge-wapproj-wont-deploy-with/1400477
> Add <SkipImportNetSdk>

- .github/workflows/build-frontends.yml
- .github/workflows/build-ilspy.yml
- .github/workflows/codeql-analysis.yml
- .vsconfig
- ICSharpCode.Decompiler.Tests/Helpers/Tester.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CS9_ExtensionGetEnumerator.cs
- ICSharpCode.Decompiler/Metadata/DotNetCorePathFinder.cs
- ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs
- ILSpy.BamlDecompiler.Tests/ILSpy.BamlDecompiler.Tests.csproj
- README.md
- global.json
> Net50 buildtools

- ILSpy.AddIn/ILSpy.AddIn.csproj
- ILSpy.AddIn/source.extension.vsixmanifest.template
> Modifications for testing for VS2022

- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.nuspec.template
> Reproducible builds

- ILSpy.Package/ILSpy.Package.wapproj
- ILSpy.WithPackage.sln
For https://github.com/icsharpcode/ILSpy/issues/2490
Could (should?) be made nicer to work like the VS Addin that copies specific files instead of the whole thing?
> Wapproj Fix

- ILSpy.BamlDecompiler.Tests/BamlTestRunner.cs
- ILSpy.BamlDecompiler/BamlDecompilationResult.cs
- ILSpy.BamlDecompiler/BamlDecompilerSettings.cs
- ILSpy.BamlDecompiler/BamlDecompilerTypeSystem.cs
- ILSpy.BamlDecompiler/BamlResourceEntryNode.cs
- ILSpy.BamlDecompiler/BamlResourceNodeFactory.cs
- ILSpy.BamlDecompiler/XamlContext.cs
- ILSpy.BamlDecompiler/XamlDecompiler.cs
/cc @CreateAndInject does this work for you?
> Fix #2337: Expose simple public XamlDecompiler API.

- ILSpy/Analyzers/AnalyzerTreeView.cs
- ILSpy/Docking/DockWorkspace.cs
- ILSpy/FilterSettings.cs
- ILSpy/MainWindow.xaml
- ILSpy/MainWindow.xaml.cs
- ILSpy/MainWindowViewModel.cs
- ILSpy/Search/SearchPane.cs
- ILSpy/SessionSettings.cs
- ILSpy/TextView/DecompilerTextView.cs
- ILSpy/TreeNodes/AssemblyTreeNode.cs
- ILSpy/TreeNodes/EventTreeNode.cs
- ILSpy/TreeNodes/FieldTreeNode.cs
- ILSpy/TreeNodes/MethodTreeNode.cs
- ILSpy/TreeNodes/PropertyTreeNode.cs
- ILSpy/TreeNodes/TypeTreeNode.cs
- ILSpy/ViewModels/ManageAssemblyListsViewModel.cs
- ILSpy/ViewModels/TabPageModel.cs
- ILSpy/Views/DebugSteps.xaml.cs
Proper fix for
* #1948
* #2404
* #2550
* #2551
> Fix typesystems used in the UI

- ICSharpCode.Decompiler.Tests/Helpers/Tester.cs
- ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
- ICSharpCode.Decompiler.Tests/ILPrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/ForLoopTests.xml
- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/HelloWorld.xml
- ICSharpCode.Decompiler.Tests/TestCases/PdbGen/LambdaCapturing.xml
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/FileScopedNamespaces.cs
- ICSharpCode.Decompiler.Tests/UglyTestRunner.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/CSharp/Syntax/GeneralScope/NamespaceDeclaration.cs
- ICSharpCode.Decompiler/CSharp/Transforms/NormalizeBlockStatements.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ILSpy/Options/DecompilerSettingsPanel.xaml.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
Implements C# 10 file-scoped namespaces.
> Generate file-scoped namespace declarations, if possible.

- ILSpy/Properties/app.config.template
- packages.props
https://github.com/icsharpcode/AvalonEdit/releases/tag/v6.1.3
> Update to AvalonEdit 6.1.3.50

- .github/workflows/build-ilspy.yml
- .github/workflows/test-reports.yml
https://github.com/phoenix-actions/test-reporting#recommended-setup-for-public-repositories
> Split Test Report Workflow

- ILSpy/Metadata/DebugDirectory/CodeViewTreeNode.cs
- ILSpy/Metadata/DebugDirectory/DebugDirectoryEntryTreeNode.cs
- ILSpy/Metadata/DebugDirectory/PdbChecksumTreeNode.cs
- ILSpy/Metadata/DebugDirectoryTreeNode.cs
- ILSpy/TreeNodes/AssemblyTreeNode.cs
Add Debug Directory sub tree nodes, with special handling for:
* CodeView
* EmbeddedPortablePdb
* PdbChecksum
Raw data column:
> Add Debug Directory raw data and sub tree nodes

- ICSharpCode.ILSpyCmd/IlspyCmdProgram.cs
> Fix allowed Language Versions

- .github/workflows/build-ilspy.yml
- ICSharpCode.ILSpyX/ICSharpCode.ILSpyX.csproj
- ICSharpCode.ILSpyX/PackageReadme.md
> Build ILSpyX NuGet package

- ILSpy/TextView/DecompilerTextView.xaml
There is no issue here
Just improve selected text highlighting, like that
Before:
After:
> Improve selected text highlighting

- ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
@cshung can you please verify? Thanks.
> Update NuGets for R2R plugin

- ICSharpCode.Decompiler.Tests/PrettyTestRunner.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CompoundAssignmentTest.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/Operators.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/TypeAnalysisTests.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpAmbience.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/CSharpOutputVisitor.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/GenericGrammarAmbiguityVisitor.cs
- ICSharpCode.Decompiler/CSharp/OutputVisitor/InsertParenthesesVisitor.cs
- ICSharpCode.Decompiler/CSharp/Resolver/CSharpOperators.cs
- ICSharpCode.Decompiler/CSharp/Resolver/CSharpResolver.cs
- ICSharpCode.Decompiler/CSharp/Syntax/Expressions/AssignmentExpression.cs
- ICSharpCode.Decompiler/CSharp/Syntax/Expressions/BinaryOperatorExpression.cs
- ICSharpCode.Decompiler/CSharp/Syntax/TypeMembers/OperatorDeclaration.cs
- ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs
- ICSharpCode.Decompiler/CSharp/Transforms/PrettifyAssignments.cs
- ICSharpCode.Decompiler/CSharp/Transforms/ReplaceMethodCallsWithOperators.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ICSharpCode.Decompiler/IL/Instructions/CompoundAssignmentInstruction.cs
- ICSharpCode.Decompiler/IL/Transforms/TransformAssignment.cs
- ICSharpCode.Decompiler/Output/IAmbience.cs
- ILSpy/Languages/CSharpLanguage.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
Implement support for `operator >>>`.
> C# 11: Unsigned right shift

- ICSharpCode.Decompiler.Tests/TestCases/Pretty/CompoundAssignmentTest.cs
- ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs
- ICSharpCode.Decompiler/CSharp/Transforms/PrettifyAssignments.cs
https://twitter.com/JdanceM/status/1664807410542821379
> Fix compound assignments involving local variables

- Directory.Build.props
Reverts icsharpcode/ILSpy#3026
> Revert "Accelerate local builds in Visual Studio"

- ILSpy/ILSpy.csproj
* https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8/#gc (more: https://maoni0.medium.com/dynamically-adapting-to-application-sizes-2d72fcb6f1ea)
* https://learn.microsoft.com/en-us/dotnet/core/runtime-config/wpf#hardware-acceleration-in-rdp
> Activate Dynamic Adaptation To Application Sizes (DATAS) and RDP hardware acceleration

- .github/workflows/build-frontends.yml
- .github/workflows/build-ilspy.yml
- .github/workflows/generate-bom.yml
Reverts icsharpcode/ILSpy#3140 due to breaking changes
> Revert "Bump actions/upload-artifact from 3 to 4"

- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/FSharpLoops_Debug.cs
- ICSharpCode.Decompiler.Tests/TestCases/ILPretty/FSharpLoops_Release.cs
- ICSharpCode.Decompiler.Tests/TestCases/Pretty/ConstructorInitializers.cs
- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
- ICSharpCode.Decompiler/CSharp/RecordDecompiler.cs
- ICSharpCode.Decompiler/CSharp/Transforms/TransformFieldAndConstructorInitializers.cs
- ICSharpCode.Decompiler/DecompilerSettings.cs
- ICSharpCode.Decompiler/NRExtensions.cs
- ILSpy/Languages/CSharpLanguage.cs
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
Open questions:
* Do we want a separate setting for this language feature? Currently there is only a setting for primary constructors in records
> Add C# 12 primary constructors

- ILSpy/AssemblyTree/AssemblyTreeModel.cs
to reflect e.g. indent size change in options tab.
> Refresh should also refresh the content of the active tab 

- Directory.Packages.props
- ILSpy/ILSpy.csproj
Not touched (first one is block list anyways)
> Update NuGet Packages, some to 9.0 outside of ICSD

- ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs
https://github.com/icsharpcode/ILSpy/issues/3355
It seems to be a simple omission issue.
> Fix #3355 : Insert missing DecompilerSettings

- .github/workflows/build-frontends.yml
- .github/workflows/build-ilspy.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/generate-bom.yml
- .github/workflows/lock.yml
https://github.com/ossf/scorecard/blob/d65d151df8593c89430e014d7e77b6e431e8880c/docs/checks.md#token-permissions
> Principle of least privilege for workflow tokens

- Directory.Packages.props
- ICSharpCode.BamlDecompiler/packages.lock.json
- ICSharpCode.Decompiler.Tests/Helpers/CodeAssert.cs
- ICSharpCode.ILSpyCmd/packages.lock.json
- ICSharpCode.ILSpyX/packages.lock.json
Difflib 2025 required a new namespace import
> NuGet updates for January 25 Patch Tuesday

- ILSpy/App.xaml
- ILSpy/App.xaml.cs
- ILSpy/Controls/ZoomScrollViewer.xaml
- ILSpy/Options/DisplaySettings.cs
- ILSpy/Options/DisplaySettingsPanel.xaml
- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
This is a fixed version of #3394.
> Fix #3393: Option to turn off smooth scrolling

- Directory.Packages.props
- ICSharpCode.Decompiler/IL/ControlFlow/StateRangeAnalysis.cs
Link to, or brief information about the issue
> Roslyn 4.13

- ILSpy/Properties/Resources.Designer.cs
- ILSpy/Properties/Resources.resx
- ILSpy/Properties/Resources.zh-Hans.resx
> Improve UI for primary constructors on non-record types

- .github/workflows/build-ilspy.yml
- ILSpy.Installer/ILSpy.Installer.csproj
- ILSpy.Installer/README.md
- ILSpy.Installer/setup.cs
- ILSpy.Installer/winui.wxl
- publishlocaldev.ps1
* Format of wxl has changed
* Build now has a PostBuild step
* Global tool for wix is used
Additional bonus: size is reduced
> Update to _wix4 packages for installer

- Directory.Packages.props
- ICSharpCode.BamlDecompiler/packages.lock.json
- ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler/packages.lock.json
- ICSharpCode.ILSpyCmd/packages.lock.json
- ICSharpCode.ILSpyX/packages.lock.json
See https://github.com/spekt/testlogger/releases for JunitXml.TestLogger changes for 6 and 6.1
> NuGet updates 04/25

- ICSharpCode.ILSpyCmd/IlspyCmdProgram.cs
- ICSharpCode.ILSpyX/Settings/DecompilerSettings.cs
- ICSharpCode.ILSpyX/Settings/SettingsServiceBase.cs
- ILSpy.ReadyToRun/ReadyToRunOptions.cs
- ILSpy/DecompilationOptions.cs
- ILSpy/LanguageSettings.cs
- ILSpy/Options/DecompilerSettingsViewModel.cs
- ILSpy/Options/DisplaySettings.cs
- ILSpy/SessionSettings.cs
- ILSpy/Updates/UpdateSettings.cs
- ILSpy/Util/SettingsService.cs
- TestPlugin/CustomOptionPage.xaml.cs
Fixes #3494
Still not really user-friendly, but it's a start...
> Add dynamic ILSpy settings options to ILSpyCmd
